CREATE TABLE category (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE recipe (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    ingredients TEXT         NOT NULL,
    preparation TEXT         NOT NULL,
    category_id BIGINT       NOT NULL REFERENCES category(id),
    view_count  INT          NOT NULL DEFAULT 0
);

CREATE INDEX idx_recipe_category ON recipe(category_id);
