-- Categories
INSERT INTO category (id, name) VALUES (1, 'Aziatisch');
INSERT INTO category (id, name) VALUES (2, 'Dranken');
INSERT INTO category (id, name) VALUES (3, 'Gebak');
INSERT INTO category (id, name) VALUES (4, 'Gevogelte');
INSERT INTO category (id, name) VALUES (5, 'Hapjes');
INSERT INTO category (id, name) VALUES (6, 'Kindergerechten');
INSERT INTO category (id, name) VALUES (7, 'Nagerechten');
INSERT INTO category (id, name) VALUES (8, 'Paddestoelen');
INSERT INTO category (id, name) VALUES (9, 'Pastas');
INSERT INTO category (id, name) VALUES (10, 'Soepen');
INSERT INTO category (id, name) VALUES (11, 'Vegetarisch');
INSERT INTO category (id, name) VALUES (12, 'Visgerechten');
INSERT INTO category (id, name) VALUES (13, 'Vleesgerechten');
INSERT INTO category (id, name) VALUES (14, 'Voorgerechten');

-- Recipes
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (1, 'Zachtgekookte eieren in mosterdsaus', '200 g. champignons|30 g. boter|1 eetlepel bloem|1dl. witte wijn|1 dl. bouillon|4 eetlepel room|2 eetlepel mosterd|beetje gehakte basilicum|dragon(of bieslook en peterselie)|8 eieren', 'Bak de champignons in de boter. Voeg er de kleingesnipperde sjalotjes bij. Strooi er 1 eetl.bloem over, roer alles door mekaar en overgiet met de witte wijn en de bouillon. Kruid met peper en zout en laat 10 min. stoven.Laat intussen de eieren zacht koken. Voeg bij de saus 4 eetl. room en de mosterd.Schik 2 gepelde zachtgekookte eieren in elk potje. Giet er de saus over.Bestrooi ze met een weinig basilicum en dragon. Ik verkies liever peterselie en bieslook! Dien meteen op. Lekker met toast of vers brood.', 14, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (2, 'Gevulde broodjes', '2 broodjes|tafelolie|300 g garnalen|2 eetlepel boter|1/2 kl.kerriepoeder|3 dl.verse room|2eetl.gehakte dille of peterselie', 'Snij het bovenste kapje van de broodjes en hol ze uit. Bestrijk ze binnenin met wat olie, en warm ze even op. (Gaat goed in de broodrooster). Fruit ondertussen de garnalen aan in de boter en bestuif ze met de kerrie. Overgiet met de helft van de room en laat indikken. Giet er de rest van de room bij en laat indikken tot een romige massa. Roer de dille of peterselie erdoor en vul de broodjes.', 14, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (3, 'Schep-ei', 'Eieren (volgens aantal pers.)|boter|bloem|beetje bouillon|verse room|peterselie|bieslook|dille|1 eetlepel kappertjes|beetje citroensap|peper en zout', 'Maak een roux met de boter, de bloem en de warme bouillon. Eierdooier onder de room mengen en door de iets afgekoelde roux mengen. Ondertussen de eieren hard koken (10 min. vanaf het kookpunt van het water.) Alle fijne verse kruiden, de kappertjes, het citroensap, zout en peper aan de saus toevoegen. De eieren zo warm mogelijk pellen, in partjes snijden en in de warme saus leggen. 
Simpel maar lekker. Smaakt goed met gebakken aardappeltjes.', 14, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (4, 'Vlinder om te eten', 'Een broodje|8 plakken worst|een stuk kaas', 'Met een mes snijden we de broodjes aan de zijkanten zo''n 2 cm diep in. Het middelstuk blijft gewoon zoals het is. We leggen voor elk broodje 4 kleinere plakken worst op vier grote. Dit doen we zo dat de kleine worst op één plaats tegen de rand van de grote plak ligt. Met een mesje schuiven we de plakken worst in het broodje, 2 links en 2 rechts. De vleugels van de vlinder zijn nu klaar. Voor de sprieten snijden we op een broodplank stukjes kaas af van 4 x 1 x 1 cm. Aan één van de punten van het broodje boren we met de punt van het mes twee kleine gaatjes. Daar schuiven we de stukjes kaas in. Nu heeftonze vlinder ook lekkere sprieten.', 6, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (5, 'Feestslang', '1 frans brood|Tandenstokers|Hesp|2 olijven|Gewassen en gedroogde sla|Gepelde tomaat in schijfjes|Hard gekookte eieren|Kaas|Mayonaise', 'Snij een frans brood in gelijke stukken. Snij in het eerste stuk een opening en steek er de in een slangetong-vorm gesneden hesp in. De twee olijven gebruiken we voor de ogen en steken we met de tandenstokers links en rechts in dit eerste stuk vast. Bestrijk de andere stukjes brood met de mayonaise en beleg ze met sla, tomaat, hesp, kaas en een paar schijfjes hard gekookt ei. Steek er vervolgens een tandenstoker in en maak ze aan elkaar vast zodat je een slange vorm krijgt.', 6, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (6, 'Bloemkool met rundergehakt', '750 gram rundergehakt|1 fijngehakte ui|1 bouillonblokje|1 eetlepel worcestersaus|1 blikje tomatenpuree|1 eetlepel bloem|1 bloemkool|1 béchamelsaus|gemalen kaas', 'Fruit het gehakt rul in een nootje boter. Voeg er de ui aan toe en laat bakken tot het vlees en de ui mooi goudbruin zijn. Doe er een verkruimeld bouillonblokje,1 eetl. worcestersaus,1 blikje tomatenpuree en 1eetl. bloem losgeroerd in wat water bij. Roer dit goed om. Kruid naar smaak en laat nog 5 min zacht sudderen. Kook intussen de bloemkool gaar, en bereid een bechamelsaus. Schep het gehakt in een vuurvaste schotel, leg er de bloemkool op, overgiet met de béchamelsaus, en bestrooi met de gemalen kaas. Laat even gratineren', 13, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (7, 'Gegratineerde koteletten', '150 gram versgeraspte gruyère|1 ei|2 eetlepels room|Koteletten|Zout|Vers gemalen peper', 'Verwarm de oven voor op 250°. Klop in een kom het ei los met de kaas en de room.
Op smaak brengen met nootmuskaat, peper en zout. Verwarm de boter in een braadpan. Bestrooi het vlees met paprikapoeder en bak halfgaar in de boter. Leg de koteletten in een vuurvaste schotel. Bestrijk ze elk met het kaasmengsel. Bedruip ze met het bakvet. In de hete oven in ca. 15 min. gaar laten worden. Dezelfde bereidingswijze is ook geschikt voor kipfilet.', 13, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (8, 'Gehakt op de wijze van Nice', '1 ei|Melk|Zout en peper|1 kl. gedroogd basilicum|chapelure|1 gehakte ui|1 geplet knoflookteentje|500 gram gehakt|Enkele aardappelen|2 grote uien|margarine|1/4 kl. gedr. dragon|1/4 gedr. basilicum|2 eetl. gehakte peterselie|Enkele tomaten|Gemalen kaas', 'Meng het gehakt met ei(dooier), wat melk, chapelure, zout peper en wat basilicum en een beetje fijn gehakte ui en de knoflook. Kneed alles tot een homogeen geheel. Strijk het gehakt mooi uit in een platte taartvorm. Kook de aardappelen bijna gaar en schik ze in plakjes op het gehakt. Snij de uien in ringen. Laat even aanfruiten en schik op de aardappelen. Bestrooi met wat peper, kruidnoot, de dragon, basilicum en peterselie. Leg de plakjes tomaat er boven op en bestrijk met wat gesmolten boter. Kruid naar smaak. Bestrooi met gemalen kaas en wat boterklontjes. Laat 30 min. in de oven gaar worden en gratineren. Bestrooi met peterselie en serveer dadelijk.', 13, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (9, 'Mini Loempias - Filipijnse stijl', '1/2 kg Gehakt Runds/varkens/kip|1 rode paprika|1 ui|1 teentje look|1/4 kg princessebonen|1 wortel|1 pak sojascheuten|sojasaus|een klein beetje peper en zout|1 ei|klein beetje bakolie', 'Snij de groenten in fijne stukjes (behalve de sojascheuten). Verwarm de pan met een klein beetje olie en voeg look, ui en vlees toe. Wanneer dit half gaar is voeg de fijngesneden groenten en sojasaus toe. Voeg peper en zout toe en laat half gaar koken. Neem de groentenmix vervolgens uit de pan en laat afkoelen gedurende 2 uur. Pers het water eruit en zet opzij. Klop het eigeel in een kleine kom. Neem één voor één de mini loempiavellen en vul ze met de groentenmix. Gebruik het eigeel om de randen aan mekaar te kleven. Bak de loempia''s vervolgens in frituurvet (180°C) ongeveer 3 tot 5 minuten.', 1, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (10, 'Karbonade met bieslook en tomatenboter', '125 g boter of margarine|Zout|Een ietsje cayenne peper|Tomatenpuree|1 theelepel paprikapoeder|4 karbonades|1 theelepel kerriepoeder|Peper|Verse bieslook', '125 g boter mengen met zout, tomatenpuree, paprikapoeder, peper en snufje cayennepeper. In spuitzak doen en op bordje 4 torentjes spuiten. In de koelkast zetten. Karbonades inwrijven met kerriepoeder, zout en peper. De karbonades gaar bakken. Intussen de bieslook boven plat bord fijnknippen. Karbonades vlak voor opdienen door bieslook wentelen. Garneren met botertorentje.', 13, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (11, 'Ragoï¿½t', '500 gr. kalfsfricandeau|1/2 l. groentenbouillon|500 gr. champignons|2 uien|50 gr. boter|20 gr. bloem|2 eierdooiers|1/8 l. slagroom|4 el. witte wijn|zout en peper|1-2 tl. citroensap|Worcestershiresaus|40 gr. geraspte kaas', 'De fricandeau in blokjes snijden, en aan alle kanten bruinen in de stoompot. Er dan de bouillon bij gieten en in 30 min. gaar stomen. De champignons schoonmaken en halveren. De uien pellen en snipperen. Fruit de uien glazig in de boter en voeg de champignons toe en laat meebakken. De bloem al roerend over de champignons strooien. Het vlees met een schuimspaan uit de bouillon nemen. De bouillon al roerend bij de champignons gieten en het geheel 10 min. laten koken. Eierdooiers met room losroeren en van het vuur af door de saus roeren. Op smaak brengen met zout, peper en worcestershiresaus. Het vlees door de saus roeren. De ragoï¿½t overscheppen in vuurvaste schotel, de geraspte kaas erover strooien. De schotel in voorverwarmde oven van 200ï¿½ 10 ï¿½ 15 min. laten gratineren. 
Lekker met rijst.', 13, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (12, 'Waterijsjes', '800 ml puur vruchtensap -  bijvoorbeeld sinaasappel- cranberry- of perensap of een bodempje pure vruchtensiroop aangelengd met water|Lepel|IJslollyvormpjes - 10 stuks|Vriezer|Pers (optioneel)|200 gram basterdsuiker (optioneel)', 'Waterijs is eigenlijk niet meer dan bevroren vruchtensap of siroop dat eventueel gezoet is met suiker. Om van je waterijs geen caloriebom te maken, kun je het beste puur vruchtensap of siroop gebruiken: sap dat alleen natuurlijke suikers bevat en geen toegevoegde suikers. Helemaal lekker is het als je de vruchten zelf perst. Dit kun je bijvoorbeeld doen met sinaasappels, grapefruits, citroenen en limoenen. Van vruchten zoals peren, appels, cranberrys, bessen en druiven, kun je in de meeste supermarkten of natuurwinkels flessen puur sap of siroop kopen. Kies je favoriete vruchtensap en schenk zon 800 ml ervan in een kom. Je kunt ook sappen combineren. Cranberry- met sinaasappelsap is bijvoorbeeld een heerlijke combinatie. Net zoals peren- en appelsap. Als je liever vruchtensiroop gebruikt in plaats van sap, dan heb je slechts een klein beetje nodig. Je lengt het bodempje siroop vervolgens aan met water totdat je een hoeveelheid hebt van 800 ml. Dit is genoeg voor ongeveer 10 waterijsjes. Sommige vruchtensappen kunnen wat zuur zijn. Door wat suiker aan het sap toe te voegen, kun je de zure kantjes van het sap afhalen. Hou je juist van dat zure, laat dan de suiker achterwege. Of als je liever niet te veel suiker binnenkrijgt, kies dan voor een wat zoetere vrucht zoals peren of aardbeien. Voor het zoeten van het vruchtensap kun je het beste basterdsuiker gebruiken. Basterdsuiker heeft een veel fijnere structuur dan kristalsuiker. Je waterijsjes vormen hierdoor meer een geheel, ze worden gladder. Als je waterijsjes maakt van de wat zuurdere vruchtensappen zoals cranberry- of grapefruitsap, kun je 200 gram basterdsuiker toevoegen als je 800 ml sap gebruikt. Doe de suiker bij het sap in de kom en roer tot de suiker volledig is opgelost. Bij kookwinkels kun je ze krijgen, maar ook bij huishoudzaken als de Blokker of Xenos vind je de plastic ijslollyvormpjes. Spoel de vormpjes af en maak ze droog. Vul ze vervolgens met het vruchtenmengsel en steek de stokjes erin. En dan moet de vriezer zijn werk gaan doen: plaats de vormpjes in het vriesvak en haal ze er pas weer uit als de lollys volledig bevroren zijn. Hoe lang dat duurt, hangt af van de vrieskracht van je apparaat, maar meestal zijn je lollys wel na een uurtje of drie klaar. Likken en genieten maar!', 6, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (13, 'Roergebakken varkenshaasje met groenten', 'Marinade|1 koffielepel sojasaus|1 koffielepel sherry|1 koffielepel sesamolie|----------------|Varkenshaasje|2 wortelen|300 gr.peultjes|12 baby-maïskolfjes|12 shii-takes|3 lente-uitjes|Arachide-olie|1 teentje knoflook|Stukjes verse gember|Sojasaus|2 à 3 eetlepels maïzena', 'Vermeng de ingrediënten voor de marinade. Snij het vlees in reepjes en leg ze in de marinade. Laat 15 à 20 min trekken. Maak ondertussen de groenten schoon. Snij de wortelen in schuine plakjes. Haal de peultjes af en laat ze heel. Snij de maïskolfjes in rondjes. Snij het steeltje van de shii-takes en halveer de hoedjes. Snij de paprika''s in reepjes en snij de lente-uitjes in ringetjes. Hou een beetje groen apart voor de afwerking. Verhit een beetje olie in de wok en roerbak er op hoog vuur de gemarineerde reepjes varkensfilet in.Neem de reepjes uit de wok en laat ze uitlekken in een zeef. Snipper de gepelde knoflook en de verse gember fijn. Maak de wok schoon en doe er opnieuw een beetje olie in. Roerbak de groenten. Eerst de wortelen, dan maïs, de peultjes, de paprika''s, de knoflook en de gember. Blijf voortdurend omscheppen ! Doe er de paddestoelen bij en tot slot de lente-uitjes. 
Roer het maïszetmeel los in de fond met een scheutje sojasaus. Overgiet er al roerend de groenten mee. Meng er het vlees door en laat alles nog een paar minuten doorwarmen. Werk het gerecht af met het apart gehouden groen van de lente-uitjes.', 13, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (14, 'Garnalenragout op oosterse wijze', '1 kg. garnalen|1 dikke ui|2 knoflookteentjes|2 eetlepel boter|1 dl. cognac|2 eetlepel paprikapoeder|1/4 k.lepel cayennepeper|2 dl. verse room|1 (groene) paprikac', 'Laat de gehakte ui samen met de gesnipperde knoflook en de in reepjes gesneden paprika aanfruiten in de gesmolten boter. Voeg de garnalen toe en laat 5 min. doorstoven. Overgiet met de cognac, laat opwarmen en flambeer. Roer er dan de verse room door en kruid met de cayennepeper en paprikapoeder. Laat op een hoog vuur indikken en serveer met rijst of een slaatje. Lekker en vlug klaar.', 1, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (15, 'Gegratineerde mosselen', '2 kg. mosselen|3 sjalotjes|1 citroen|2 eieren|2 lepels bloem|1 hand vol broodkruim|130 gram boter|50 gram gemalen gruyére|1 glas witte wijn|Peterselie|Zout en peper', 'Doe de gereinigde mosselen in een kookpot en strooi er de gehakte sjalotjes, zout, peper en de witte wijn. Laat de mosselen gaar koken op een hevig vuur. Na kooktijd laat u de mosselen uitlekken en bewaart u het kookvocht. Ontdoe de mosselen van hun schelp. Beboter een vuurvaste schotel en leg er de mosselen in. Bereid met een gedeelte van de boter en 2 lepels bloem een blonde roux. Voeg er, beetje bij beetje, het gezeefde kookvocht aan toe. Roer de saus tot ze glad en gebonden is. Voeg er de eierdooiers aan toe en laat de saus eventjes doorkoken op een zacht vuur onder voortdurend roeren. Neem de saus van het vuur en meng er het citroensap door. Bedek de mosselen met de saus. Bestrooi met het broodkruim en de geraspte kaas. Verdeel de nootjes boter over de schotel en laat in een zeer warme oven gratineren gedurende 5 min. Bestrooi met gehakte peterselie en dien zeer warm op met een droge witte wijn. Lekker met mooi gespoten puree aardappels.', 12, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (16, 'Bloemkoolsoep met kaas', '3 liter kooknat van bloemkool|90 gram boter|90 gram bloem|100 gram gemalen kaas|Gehakte peterselie|1 1/2 dl room of melk|1 a 2 eierdooiers', 'Maak een roux, die aanlengen met kooknat van bloemkool, eventueel aangelengd met bouillon. De soep laten doorkoken en er als versiering kleine stukjes bloemkool aan toevoegen; laten doorkoken. Meng in de soepkom de eierdooier(s), room of melk, peterselie en gemalen kaas. Giet er de kokende soep op en dien op.', 10, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (17, 'Gevulde speculaas', '250 gram zelfrijzend bakmeel|Zout naar smaak|2 eetlepels speculaaskruiden|150 gram bruine basterdsuiker|150 gram boter|2 eetlepels melk|50 gram witte amandelen|1 eierdooier', 'Het zelfrijzende bakmeel met wat zout, de speculaaskruiden en de basterdsuiker in een kom doen. De boter hierin met twee messen kleinsnijden. De melk toevoegen en van dit alles een deeg kneden. De helft van het deeg uitdrukken op een beboterde bakplaat - als een staaf, rechthoek of hartvorm. Het amandelpers hierover uitspreiden to 1 cm van de rand af. De tweede deeghelft erop leggen en deze goed aan de rand aandrukken. Versieren met de amandellen. De bovenkant bestrijken met de eierdooier die is losgeroerd met de melk. De bakplaat iets onder het midden van een matig warme oven ongeveer 150 graden C schuiven. Baktijd: 1/2 ? 3/4 uur tot de koek gaar en goudbruin van kleur is. De gevulde speculaas vlakliggend laten afkoelen.', 3, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (18, 'Aardbeienbavarois', '3 blaadjes gelatine van elk 3 gram|200 gram aardbeien|25 gram griessuiker|2.5 dl. room|--- Voor de spiegel en coulis ---|1 blaadje gelatine van 3 gram|50 gram griessuiker|200 gram aardbeien|scheutje cointreau|--- Voor de afwerking ---|250 gram aardbeien|blaadjes citroenmelisse|satéstokjes|4 vormpjes van ongev. 8cm diameter', 'Week de gelatineblaadjes (3+1) in koud water. Spoel de aardbeien en verwijder de kroontjes. Kook het water met de suiker tot een stroopje en laat afkoelen. Snij voor de coulis 200 gr. aardbeien in stukjes, voeg ze toe aan het stroopje en mix ze fijn. Zeef de coulis en parfumeer deze met een scheutje cointreau. Knijp 1 gelatineblaadje uit, smelt het op een laag vuur en roer door de helft van de coulis. Zet de andere helft van de coulis koel weg. Giet een bodempje gelei in de vormpjes. Snij 8 aardbeien in plakjes en zet ze met de punt naar beneden in cirkelvorm tegen de kant van de vormpjes. Mix voor de bavarois de aardbeien met de griessuiker. Klop de room met de vanillesuiker. Hij mag niet helemaal stijf zijn. Knijp de resterende gelatineblaadjes uit, smelt ze en roer ze zorgvuldig door de aardbeienpuree. Spatel de opgeklopte room door de aardbeienpuree en vul de vormpjes met dit mengsel. Strijk de bovenkant glad en laat ongeveer 2 uur opstijven in de koelkast. Maak spiesjes door afwisselend aardbeien en blaadjes citroenmelisse op prikkers te steken. Ontvorm de bavarois door met een mespunt de rand los te maken en de onderkant van de vormpjes even in warm water te dompelen. Werk af met een paar druppels coulis en een spiesje. Serveer de rest van de coulis er apart bij.', 7, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (19, 'Roergebakken kip met groenten', 'Kipfilet|2 wortelen|300gr. peultjes|12 baby-maïskolfjes|12 shii-takes|2 paprika''s|3 lente-uitjes|arachide-olie|1 teentje knoflook|stukjes verse gember|6 eetlepels kalfs- of gevogelte fond|sojasaus|2 à 3 eetlepels maïzena', 'Vermeng de ingrediënten voor de marinade. Snij de kip in reepjes en leg ze in de marinade. Laat 15 à 20 min trekken. Maak ondertussen de groenten schoon. Snij de wortellen in schuine plakjes, haal de peultjes af en laat ze heel. Snij de maïskolfjes in rondjes, snij het steeltje van de shii-takes en halveer de hoedjes. Snij de paprika''s in reepjes en snij de lente-uitjes in ringetjes. Hou een beetje groen apart voor de afwerking. Verhit een beetje olie in de wok en roerbak er op hoog vuur de gemarineerde reepjes kipfilet in. Neem de reepjes uit de wok en laat ze uitlekken in een zeef. Snipper de gepelde knoflook en de verse gember fijn. Maak de wok schoon en doe er opnieuw een beetje olie in. Roerbak de groenten : eerst de wortelen, dan maïs, de peultjes, de paprika''s, de knoflook en de gember. Blijf voortdurend omscheppen ! Doe er de paddestoelen bij en tot slot de lente-uitjes. Roer het maïszetmeel los in de fond met een scheutje sojasaus. Overgiet er al roerend de groenten mee. Meng er de kip door en laat alles nog een paar minuten doorwarmen. Werk het gerecht af met het apart gehouden groen van de lente-uitjes.', 4, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (20, 'Romeinse filet', '1 kg varkensgebraad|Boter|1/8 l. witte wijn|125 gr. slagroom|150 gr. halfoude kaas|Mosterd', 'Laat het gebraad gaar worden. Maak om de 2cm.een insnijding en breng in elke insnijding een snede kaas, ingesmeerd met mosterd. Laat gratineren in de oven zodat de kaas smelt. Breng het vlees op een schotel en houd het warm. Voeg de wijn bij het braadvocht. Bind de saus met de in de room opgeloste bloem. Giet een deel van saus op het vlees en dien de rest afzonderlijk op. 
Tip : Braadtijd varkensvlees - 60 min. per kg . 
----- Variatie: ----- Inplaats van 1 snee kaas en 1 snee hesp tussen het gebraad - doe als volgt: 
Hak sjalotjes "zeer fijn" alsook de champignons. Bereid een bechamelsaus en doe daar een beetje van onder het sjalot/champignonmengsel. Smeer dit op de snee hesp en steek tussen het gebraad. Doe veel kaas in de bechamelsaus en giet over het vlees. Grill in de oven.', 13, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (21, 'Schnitzels met mozzarella', '2 varkenssauté''s van 100 gr.|2 eetlepels olijfolie|2 teentjes knoflook|fijn gehakt|1 pak gezeefde tomaten (500 gr.)|1 eetlepel kappertjes gedroogde|zout en peper|1 bolletje mozzarella in 4 plakken', 'Vlees plat slaan. Ollie verhitten en de knoflook er zachtjes in bakken. Vlees toevoegen en aan één kant bruin bakken. Gezeefde tomaten erover verdelen. Kappertjes en oregano toevoegen en het vlees met deksel op de pan ongev. 8 min. laten stoven. Met zout en peper bestrooien. Op elk stukje vlees een plakje mozzarella leggen en met deksel op de pan ongeveer 2 min. laten smelten. Lekker met rijst en bijv. prinsessen. Doordeweeks gerecht.', 13, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (22, 'Servisch varkensvlees', '4 varkens sauté''s|2 eetlepels Franse mosterd|1 eierdooier|2 eetlepels bloem|1 kl. paprikapoeder|zout|3 eetlepels boter|50gr. rookspek|2 uien|2 paprika''s|4 tomaten (of gebruik enkel de tomaten van een blik gepelde tomaten - geen sap!)|peterselie|--- Voor de risotto: ---|1 ui|2 eetlepels boter of olie|2 dl.rijst|4 dl.bouillon|doos erwtjes', 'Begin met de risotto:
Fruit de gehakte ui in de boter, voeg de rijst toe, laat even doorstoven en overgiet met de bouillon. Leg een deksel op de pan en laat 20 min. stoven tot de rijst al de bouillon opgeslorpt heeft. Klop het ei los met de mosterd en strijk dit mengsel over het vlees.Wentel ze aan beide kanten door de met paprikapoeder en zout gekruide bloem.Verhit de boter en baak het vlees aan beide kanten mooi bruin. Draai het vuur lager en laat zachtjes gaar bakken. Snij het rookspek, de schoongemaakte paprika''s en de gepelde uien en de tomaten in stukjes. Laat de uien en het spek aanbakken in de pan tot ze mals zijn. Voeg de kleingesn. paprika''s toe, laat enkele min. mee fruiten en meng de stukjes tomaat erdoor. Leg een deksel op de pan en laat even doorstoven.Meng de erwtjes door de risotto. Roer er nog een klontje boter door en schep de risotto op een verwarmde serveerschotel. Leg het vlees erop en verdeel daarover het groentemengsel. Versier tot slot met in ringen gesneden uien en bestrooi met versgehakte peterselie. 
Serveer dadelijk.', 13, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (23, 'Varkenshaasje met sinaasappelsaus', '2 varkenshaasjes|zachte mosterd|candico ( kandysuiker bruin!)|6 sinaasappelen|room', 'Wrijf de varkenshaasjes in met een goeie laag mosterd, Vervolgens doe je er candijsuiker op (rijkelijk). Je laat dit even staan marineren. Intussen kunt u de sinaasappelen persen (1/2 overhouden). Die halve sinaasappel snij je in schijfjes. Verwarm de oven op 200 graden en voeg het sinaasappelsap erbij! niet alles. Als het vlees klaar is hou je dit even warm. Je neemt een steelpannetje waar je het vocht uit de overslede in doet, vul aan met room en laat even inkoken, Je kunt nog extra sinaasappelsap bijvoegen (naar smaak). Laat inkoken tot een gewenste dikte. Snij het vlees in plakjes en garneer op een warm bord, Wat kroketjes of pomme du chesse en napeer de saus over het vlees ! Afwerken met wat groen', 13, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (24, 'Kabeljauw met groenten', '1 redelijke wortel|1 flinke (of 2 dunne) soepprei(en)|2 stukken diepvries|Kabeljauw (of koolvisfilets)|Tomatenpuree|Blokje groentenbouillon opgelost in iets meer dan 1 dl water en 1 dl witte wijn (FRUITS DE MER)|Room of melk', 'Was de groenten, snij de prei in dunne en korte reepjes en snij de wortel met de dunschiller in dunne reepjes en daarna in kleine stukjes. Stoof de groenten +/- 10 min. in boter, voeg de bouillon en de wijn toe en breng aan de kook. Leg de vis (niet ontdooien) in de groentensaus en laat +/- 15 min. koken tot alles gaar is. Neem de vis en de groenten uit de pot en versier op een bord. Los in het overgebleven vocht de tomatenpuree samen met een flinke scheut melk (of room) en bind met maizena. Dien op met aardappelpuree.', 12, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (25, 'Kabeljauw met mosterdsaus', '400 g visfilets (uit de vriezer - bijv. kabeljauw - roodbaars - wijting ...)|400 g (diepvries) groenten (bijv. worteltjes en erwtjes - paprikasnippers - prei of een groentemengseltje)|1/2 l visbouillon (blokje)|3 eetlepels mosterd|2 eierdooiers|Boter|Zout en peper', 'Smelt een nootje boter in een diepe braadpan. Fruit daarin de groenten. Kruid ze naar smaak en laat zachtjes gaarstoven. Breng de visbouillon aan de kook en pocheer daarin de visfilets. Laat ze goed uitlekken en hou ze warm. Laat de visbouillon tot de helft inkoken. Roer, van het vuur, de eierdooiers en de mosterd door de saus. Laat ze nog even verwarmen maar niet meer koken! Breng op smaak en overgiet vis en groenten met de mosterdsaus. Serveer meteen. Dit gerecht is lekker met aardappelbolletjes of croquetten.', 12, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (26, 'Kabeljauw met witte wijnsaus', '4 mooie kabeljauwmoten|1/2 l fijne visfumet|1/2 l droge witte wijn|Versgemalen peper en zout|100 gram roomboter|Vers gehakte bieslook.', 'De kabeljauwmoten kruiden met peper en zout en gaar pocheren in de fumet met de witte wijn. De vis uit de pan scheppen en het kookvocht stevig laten inkoken. Doorzeven in een kleinere pan en er met klontjes de koude roomboter doorkloppen, tot er een mooi gebonden saus ontstaat. Serveren met puree, die even werd gegratineerd in de oven of onder de grill.', 12, 4542);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (27, 'Witloof met zalmvulling', '4 stronkjes witloof|+/- 125 gram champignons|2 sjalotjes|1 blikje zalm|Citroen|Een beetje witte saus|1 eierdooier|2 eetlepels room|1 mespunt hot curry|gemalen kaas|peterselie|En indien gewenst garnalen', 'Maak het witloof schoon en laat het mooi bruin worden in een beetje boter en kruid goed met peper en kruidnoot tijdens het stoven. Als het aan alle kanten mooi bruin is er bouillon bij gieten en zachtjes gaar laten worden. Snij de stronkjes midden door als ze wat dik zijn, zo zijn ze sneller zacht. Snipper ondertussen de sjalot en de champignons fijn. Open het blikje zalm, doe het vocht in een pannetje, samen met het sap van een citroen, wat boter en de gehakte groenten. Stoof dit 5 min. onder deksel. Doe de witte saus bij de gestoofde groenten, laat tegen het kookpunt komen en voeg de met room losgeklopte eierdooier plus wat gemalen kaas aan de bereiding toe. Neem van het vuur. Ontdoe de zalm van vel en graatjes, verdeel in stukjes, en meng samen met de curry onder de saus. Wrijf een ovenschotel in met boter, maak een mooie rand van lekker gekruide pureeaardappeltjes. Leg in het midden het gestoofde witloof en schep daarop de saus. Strooi daarover de rest van de gemalen kaas en laat even gratineren onder de hete grill. Je kunt de saus nog feestelijker maken door ook nog garnalen toe te voegen!', 12, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (28, 'Zalm in witte wijnsaus', '4 zalmfilets (4X150 gram)|4dl. droge witte wijn|3 sjalotjes|Boter|Bieslook|Peper en zout|250 ml. room (Alpro soya cuisine.)', 'Hak de sjalotjes fijn en smoor ze in een weinig boter. Voeg de witte wijn toe en laat inkoken tot de helft (eventueel binden met maïzena) Wrijf de stukken zalm in met peper en zout en bak ze in wat boter. Laat de room tot de helft inkoken en roer er, van het vuur de ingekookte witte wijn en de sjalotjes bij. Overgiet de gebakken zalm met de saus en versier met het versnipperde bieslook. Dien op met groene tagliatelle of aardappelpuree', 12, 13722);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (29, 'Zeetongreepjes met pistacheboter', '8 zeetongfilets|100 gr. melkerijboter|150 g. gepelde pistachenoten|Peper en zout', 'Snij de zeetongfilets in reepjes en plet de gepelde pistachenoten. Laat de melkerijboter smelten en doe deze tongreepjes en de pistachenoten erbij. Laat de reepjes gaar worden en serveer dit dan in eierschaaltjes met een klein garnituurtje erbij.', 12, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (30, 'Picatta a la Milanese', '4 kipfilets a 100gr.|Witte peper|zout|3 eetlepels tarwebloem|4 eieren|4 eetlepels geraspte Parmezaanse kaas|6 eetlepels slaolie|1/2 dl. droge witte wijn|1 eetlepel slagroom|1/8 liter slagroom|100gr. boter|50gr. roquefort|2 takjes peterselie', 'Bestrooi de kipfilets met peper en zout en bestuif ze met wat bloem. Klop een egaal beslag van de rest van de bloem met de eieren, de geraspte kaas en peper en zout naar smaak. Haal de kipfilets door het beslag en bak ze in de hete olie om en om goudgeel. Leg de filets op het bakblik en zet ze 15 min. in de oven. Breng voor de saus de wijn, de creme fraiche en de slagroom aan de kook en laat het op een hoog vuur tot ongeveer de helft inkoken. Neem de pan van het vuur en klop er de stukjes gesneden boter door. Brokkel de roquefort boven de pan en roer het door de saus. Breng op smaak met peper en zout en serveer met peterselie.', 4, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (31, 'Coq au vin', 'Kipfilets|100 gr. spek|40 gr. boter|12 kleine uitjes|2 borrels brandewijn|Zout|Vers gemalen zwarte peper|1 knoflookteentje|2 laurierblaadjes|1/2 l rode wijn|20 gr|boter|250 gr. champignons|1 kl. tijm|3 eetlepels water|2 eetlepels zetmeel|Peterselie', 'Spoel de kip even schoon onder koud stromend water en wrijf ze droog. Het spek in blokjes snijden en laten uitbakken in een grote braadpan. De boter toevoegen en de stukken kip daarin aan alle kanten mooi bruin laten kleuren. Pel intussen de uitjes en halveer ze. Laat ze vervolgens meefruiten in de boter met de kip en overgiet met de brandewijn. Flambeer.Kruiden met zout, peper, knoflook en laurier. Vervolgens overgieten met rode wijn en afgedekt ongeveer 30 min. laten smoren.De champignons schoonmaken en halveren. De boter in een koekepan verhitten en daarin de champignons aanfruiten. Kruiden met tijm en ze vervolgens 10 min. voor het einde van de bereiding bij de kip voegen en laten meesmoren. Schik de gebakken stukken kip met de uitjes,spek en champignons in een serveerschotel. Roer de braadbodem los, bind met losgeklopt zetmeel,laat indikken en kruid. Giet vervolgens de saus over de kip en bestrooi met de verse peterselie.', 4, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (32, 'Duivels lekkere kalkoenboutjes', '2 theelepels Franse mosterd|2 theelepels mosterd|1 eetlepel tomatenketchup|1/4 theelepel gemberpoeder|zout en zwarte peper|1/4 theelepel cayennepeper|4 ontvelde gekookte kalkoenboutjes (of kippefilet)', 'Roer de mosterd, tomatenketchup, gemberpoeder, zout en peper door elkaar en maak het sausje af met een snufje cayennepeper. Maak ondiepe sneetjes in de gekookte kippefilets en bestrijk ze met gesmolten margarine. Rol de filets daarna door het mosterdmengsel en laat ze hier een half uurtje in marineren. Verwarm de grill (oven) voor. Grill (braad) de boutjes ongeveer een kwartier. Ze zijn goed als het vlees gaar is en de boutjes knapperig bruin zijn. Lekker, zomers, smaakt goed met sla en tomaatjes en gebakken petatjes.', 4, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (33, 'Gegratineerde kip met pesto', '4 Kipfilets|2 uien|4 tomaten|6 gekookte aardappelen|2 bolletjes mozarella|4 eetlepels Pijnboompitten|2 teentjes knoflook|3 kroppen raketsla grof gehakt|Olijfolie|Peper en zout', 'Verwarm de oven voor op 200°. Pel de teentjes knoflook. Rooster 2 eetlepels PijnboomPitten droog in een pan. Mix voor de pesto de knoflook met de pijnboompitten, de sla, olijfolie, peper en zout. Snij de gepelde tomaten in partjes en de aardappelen in blokjes. Snij de bolletjes Mozzarella in plakjes. Pel de uien en snij ze in reepjes. Snij de kipfilets in blokjes en bak ze met de uienringen in hete boter goudbruin. Voeg er de partjes tomaat, de blokjes aardappel, de pesto en 2 eetlepels pijnboompitten aan toe. Schep alles goed om en beleg met de mozzarella. Zet de ovenschaal 10'' in de hete oven en nadien nog 2'' onder de grill. Serveer onmiddellijk.', 4, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (34, 'Gegrilde honing-kipfilet met spinaziesal', '2 kipfilets|1 eetlepel honing|1 teentje knoflook - geperst|1 vers rood chilipepertje - fijngehakt|sap van ½ citroen|1 eetlepel olijfolie|versgemalen zwarte peper en zout|--- Voor de spinaziesalade ---|1 eetlepel sesamzaadjes|1 teentje knoflook - geeperst|½ eetlepel sojasaus|1 eetlepel zoete sherry|1 eetlepel sesamolie', 'Vermeng de honing, knoflook, citroensap, chilipepertje en olijfolie. Roer tot de honing is opgenomen. Laat de kip hierin 30 min. marineren. Kruid de filets naar smaak met peper en zout. Bak ze in een grillpan (of op de barbecue) in 2 à 3 min. aan elke kant mooi gaar en bruin. Spoel de spinazie en laat de blaadjes goed uitlekken. Rooster de sesamzaadjes droog tot ze lichtgoud gekleurd zijn. Maal ze grof met een deegrol of in de vijzel. Doe ze dan in een slakom. Voeg er de geperste knoflook, sojasaus, sherry en sesamolie aan toe en roer tot een dressing. Meng er luchtig de spinazie door. Serveer de kipfilet op een bedje van spinaziesalade. Lekker en zomers met frans brood en Moezelwijntje.', 4, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (35, 'Pasta Met Zalmroomsaus', '2 tomaten|1 groene paprika|1 beker creme fraiche of room culinair|1 pakje kruidenkaas met kruiden (bv Paturain of van AH)|250 gram pasta naar keuze', 'Fruit de ui en de paprika in wat olie in een hapjespan. Wanneer het mengsel glazig is de tomaten erbij doen. Ondertussen de pasta koken. Daarna de zalmsnippers erbij doen. Als dit prutje even gebakken heeft, de creme fraiche en de kruidenkaas erbij doen en roeren tot alles goed gesmolten is. Eventueel op smaak brengen met wat zout, peper, oregano en basilicum. Pasta afgieten en klaar! 
Eventueel serveren met een lekkere salade en een glaasje wijn.', 9, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (36, 'Pasta met gehakt en gorgonzolasaus', '250 g rundergehakt|1 eierdooier|1/2 theelepel Italiaanse keukenkruiden|zout en peper|chapelure|150 gram groene tagliatelle|Boter of margarine|1/8 l slagroom|125 gram gorgonzola kaas', 'Meng in een kom:gehakt, eierdooier, kruiden, zout en peper en chapelure. Rol gehaktballetjes. In een pan de pasta beetgaar koken. Boter verhitten in een pan en de gehaktballetjes rondom goudbruin en gaar bakken. Intussen in een steelpan slagroom en gorgonzola al roerend verwarmen. De pasta in een vergiet laten uitlekken en over 2 borden verdelen. Saus erover schenken en gehaktballetjes toevoegen.', 9, 4356);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (37, 'Pizza met champignons', 'Kant-en -klare pizzabodem|2 eetlepels olijfolie|1 teentje knoflook uitgeperst|Tomatensaus|100 gram ham|250 gram champgnons in plakjes|Ietsje oregano', 'Maak eerst een tomatensaus. Stoof daarvoor een gesnipperde ui in wat boter of olijfolie en voeg geperste knoflook en een doos gepelde tomaten toe. Breng op smaak met peper zout en kruiden. Laat stoven tot het vocht verdampt is. Rol het deeg een ietsje uit, en buitenrand iets omhoog vouwen. Knoflook door 1 eetl olie roeren en de pizzabodem er dun mee bestrijken.0f gebruik lekkere pizza-olie waaraan je niets meer moet toevoegen. Tomatensaus over pizzabodem verdelen en ham erop leggen. 1 eetl. olie verhitten en champignons +/- 4 min. Omscheppend bakken. Op de ham scheppen en met kaas en oregano bestrooien. Pizza in midden van de oven 15 à 20 min. goudbruin bakken. Lekker en vlug klaar. Eventueel kan nog courgette toegevoegd worden.', 9, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (38, 'Spaghetti met geroosterde paprika', '2 rode paprika''s|2 gele paprika''s|400 gram spaghetti|olijfolie|1 teentje knoflook|Zout en peper|100 gram pecorino kaas|Peterselie', 'Paprika''s op enkele plaatsen inprikken. Boven gasvlam roosteren tot vel bruin wordt. +/- 2 min. in een afgesloten plastiek zak doen. Uit de zak nemen en vel eraf trekken. Zaadlijsten verwijderen en paprika''s in repen snijden. Spaghetti beetgaar koken. Afgieten. In een koekepan olie verhitten. Knof- look er boven uitpersen. Spaghetti en paprika erdoor scheppen. Op smaak brengen met zout en peper. Bestrooien met pecorino en peterselie. Bij gebrek aan pecorino kun je ook parmezaan gebruiken.
Lekker - ook goed als zomers voorgerecht.', 9, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (39, 'Tagliatelle met knoflooksaus', '5OO g tagliatelle (of andere noedels)|Olie|Zout|1 eetlepel margarine|2 teentjes knoflook|2OO gram kruidenkwark (Boursin - Paturain of zoiets)|1/8 l room|Peper|Gemengde tuinkruiden (diepvries)', 'Breng een ruime pan water aan de kook. Voeg zout en wat olie toe en kook de deegwaren bijtgaar. Laat ondertussen de margarine smelten. Pers er de teentjes knoflook in uit. Laat de kwark smelten en kruid nog bij met peper en de tuinkruiden. Giet de deegwaren af en overgiet met de knoflooksaus. Dien meteen op.', 9, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (40, 'Tagliatelle met prei en gehakt', '300 gram tagliatelle|Zout en peper|50 gram boter|1 kg prei in dunne ringen|2 dl room|500 g gehakt|+/- 1 dl vleesbouillon|2 el fijngesn. basilicum|Nootmuskaat|75 grof gemalen kaas', 'Tagliatelle in ruim kokend water met zout beetgaar koken en laten uitlekken. Oven voorverwarmen op 200° C. Boter verhitten en prei hierin +/- 5 min op zacht vuur bakken. Room, zout en peper toevoegen en nog +/- 10 min. stoven. Boter verhitten en gehakt in enkele min. al omscheppend rul bakken. Gehakt mengen met beetje room, bouillon,basilicum, zout, peper en nootmuskaat. Tagliatelle op de bodem van een ovenschaal leggen, gehakt erover verdelen. Met prei afdekken en kaas erover strooien.
Ongeveer +/- 30 minuten laten bakken.', 9, 17193);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (41, 'Zalm Ravioli', 'Moot zalm van +/- 300 gram|1 bos basilicum|200 gr mascarpone|2 eieren|300 gram fijn bloem|2 dl water|100 gram roomboter|1 dl room|2 tomaten|Bosje peterselie|Olijfolie|Zout en peper', 'Voorbereiding (deeg maken):
Doe de bloem in een kom en maak in het midden een kuiltje. Doe in een andere kom 1 ei, 2 dl.water, 1 theelepel zout, en een scheutje olijfolie, klop dit door elkaar met een garde en giet dit mengsel in het kuiltje in de bloem. Meng alles door elkaar tot er een gladde massa ontstaat. Doe plastic folie over de kom en zet het een paar uur gekoeld weg. Snij de zalm in blokjes. Voeg 1 ei, grof gesneden basilicum, mascarpone,en zout en peper toe. Geheel goed mengen. Rol het deeg uit tot dunne vellen, leg een lasagnevel op het werkblad. Zorg ervoor dat er een kommetje met een geklutst ei en een kwastje klaarstaat. Maak het deeg met het kwastje nat. Breng nu met een lepel de vulling in kleine hoopjes op het deeg aan, ongeveer 5 cm afstand houden tussen de hoopjes. Neem een ander deegvel en leg het op het geheel, goed aandrukken waar geen vulling is. Snij nu met een ravioliwiel het gewenste model, lrt er wel op dat de buitenkant van de ravioli goed gesloten is. Breng een pan met ruim water aan de kook. Voeg wat zout toe. Doe de ravioli er voorzichtig in en laat dit ongeveer 4 a 5 minuten koken. Laat in een koekenpan wat boter smelten,Voeg twee ontvelde in in blokjes gesneden tomaten toe laat dit ongeveer 2 minuten bakkken. Voeg de fijn gehakte peterselie, zout en peper toe. Haal de ravioli voorzichtig met een schuimspaan uit de pan en voeg dit voorzichtig aan de saus toe, laat het geheel 
ongeveer 5 minuten staan, dan meteen serveren.', 9, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (42, 'Fijne amandelcake', '110 gram boter|140 gram kristalsuiker|85 gram gemalen amandelen|3 eieren|40 gram bloem|1/2 theelepel bakpoeder|Mespunt zout|Poedersuiker voor de versiering', 'Boter zacht roeren en met de suiker mengen tot ze schuimend en dik is. Amandelen toevoegen en nog even kloppen. Geleidelijk de eieren door het beslag werken. Steeds kloppend met de handmixer. Tenslotte bloem, bakpoeder en zout zorgvuldig door het eiermengsel spatellen. In de ingevette cakevorm (18 cm) scheppen en in de warme oven (180°) Laten bakken tot de cake goudbruin is en veerkrachtig.(45 min.) Op het taartrooster laten afkoelen en voor het opdienen met poedersuiker bestuiven.', 3, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (43, 'Amandeltaart met appel', '150 gram amandelen|75 gram boter|2 eieren|100 gram suiker|100 gram room|3 appelen (reinetten)', 'Doe de gezeefde bloem en een snufje zout in een ronde kom, en kneed de stukjes boter er doorheen. Voeg bij beetjes koud water toe, tot u een bol kunt kneden. Laat een paar uur rusten op een koele plaats. Strooi bloem op het werkvlak en rol het deeg dun uit. Leg het in een beboterde taartvorm. Snij de appelen in partjes en schik ze op het deeg. Ontvel de amandelen. Mix de amandelen, de suiker, de room, en de eieren en giet dit over de appelen. Bak ongev. 40 min. in een voorverwarmde oven van 200° C.', 3, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (44, 'Ananasbavarois met aardbeiencoulis', '--- Voor de aardbeiencoulis: ---|1/2 kg. aardbeien|Bloemsuiker naar eigen smaak|Enkele druppeltjes citroen|--- Voor de ananasbavarois: ---|4 dl. ananaspuree|4 dl. opgeklopte room|7 gelatineblaadjes|2 dl. water|150 gram suiker|Enkele druppeltjes citroen|---- Voor de versiering: ----', 'Mix - voor de collies - de aardbeien, de bloemsuiker en de citroen en zeef de collies. Laat het water en de suiker koken tot siroop. Voeg de geweekte en uitgeknepen gelatineblaadjes toe en laat het geheel afkoelen. Voeg de siroop bij de ananaspuree, samen met de citroen en spatel er de opgeklopte room onder. Giet het mengsel in geoliede vormpjes en laat ze opstijven in de koelkast. Keer ze om op een bord. Schik het seizoenfruit en de collies er decoratief rond. Afwerken met een blaadje munt.', 7, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (45, 'Appelcake', '125 gram zelfrijzende bloem|150 gram fijne suiker|1 pakje vanillesuiker|75 gram boter|2 eieren|750 gram appels', 'Beboter de kleine cakevorm en bestuif met wat bloem. Klop de eierdooiers en de suiker witschuimig. Bewerk het mengsel 5 min. Roer er de gesmolten boter onder, en vervolgens de zelfrijzende bloem. Meng alles goed en voeg de stijfgeklopte eiwitten er onder. Voeg de geschilde en in dobbelsteentjes gesneden appels onder het beslag. Schep het appelbeslag in een lange cakevorm en zet 40 min. in een oven van 180°.
Leg alluminiumfolie over de cake als hij te donker wordt.', 3, 5002);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (46, 'Brownies met hazelnoten', '150 gram melkchocolade met stukjes hazelnoot|50 gram boter|3 eieren|150 gram griessuiker|150 gram bloem|3 eetlepels room', 'De oven voorverwarmen op 180°. De boter en de chocolade au bain-marie laten smelten. De eierdooiers loskloppen met de suiker en door de chocolade mengen. De bloem erover zeven en goed mengen. De eiwitten stijfkloppen en onder het beslag mengen. 8 kleine vormpjes invetten en met bloem bestuiven. Het beslag erin scheppen en 10 min. bakken op 180°. De thermostaat terugschakelen tot 175° en nog 10 min. verder bakken.
Laat de vormpjes afkoelen.', 3, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (47, 'Brusselse wafels', '250 gram bloem|20 gram gist|2 dl lauw water|2 dl. lauwe melk|4 eieren|125 gram ongezouten boter of vetstof|Een snuifje zout', 'Zeef de bloem in een kom en maak in het midden een kuiltje. Los de gist op in het lauwe water, roer het papje langzaam door de bloem en voeg er de lauwe melk bij, een snuifje zout en de eierdooiers. Meng alles goed. Klop de eiwitten stijf en spatel de eiwitsneeuw en de gesmolten vetstof voorzichtig onder het beslag. Laat 15 tot 20 min. rijzen voor u begint te bakken. Schep per wafel een kleine soeplepel beslag in het hete wafelijzer. Bak deze dikke, luchtige wafels in een wafelsijzer met een groot, grof ruitjespatroon. Serveer ze warm, met poedersuiker en een toef slagroom. Versier desgewenst met vers fruit.
(Om ze nog luchtiger te maken, vervangt u de hoeveelheid gewoon water door bruisend water).', 3, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (48, 'Chocolademousse', '15O g chocolade|3 eieren|80 gram suiker|1/8 l room|2 cl cognac of rum', 'Smelt de in stukjes gebroken chocolade au bain-marie. Klop intussen 3 eierdooiers met de suiker schuimig, tot de suiker opgelost is. Klop de room stijf. Klop de eiwitten stijf. Roer de cognac of rum door de dooiermassa en giet die daarna door de gesmolten chocolade. De massa moet nog lauwwarm zijn als de stijfgeslagen room erdoor wordt geroerd. Schep er daarna de stijfgeslagen eiwitten door.', 7, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (49, 'Kokosbolletjes', '100 gram geraspte kokosnoot|25 gram meel|75 gram boter of margarine|50 gram suiker|1 ei|Zout.', 'Roer de boter met de suiker, het ei en het zout tot één zacht geheel. Voeg hierbij eerst het gezeefde meel en vervolgens de kokosnoot. Meng alles goed dooreen. Beboter een bakplaat. Vorm van het deeg kleine bolletjes en leg deze op de bakplaat. Bak ze bij een zeer matige ovenwarmte (150 °) in 30'' gaar. Ze zijn goed wanneer ze lichtjes gekleurd zijn en los op de bakplaat liggen.', 3, 4428);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (50, 'Mokkaroom', '1/4 l slagroom|1 zakje slagroomversteviger|2 1/2 eetlepel witte basterdsuiker|1 eetlepel sterke koffie|1 dl chocolade pudding|4 koekjes|25 gram mokkaboontjes', 'In kom slagroom met slagroomversteviger en suiker stijfkloppen. In spuitzak 2 eetlepels slagroom scheppen. Door de rest van de slagroom koffie en chocolade pudding kloppen. Het slagroommengsel over 4 glazen verdelen en tot gebruik in de koelkast zetten. Versieren met toefje slagroomen chocolade mokkaboontjes.', 7, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (51, 'Soesjes', '1 1/2 dl. water|Snufje zout|75 gram margarine|90 gram gezeefde bloem|2 à 3 eieren', 'Breng het water met wat zout en de margarine al roerend aan de kook. Van het vuur ineens de gezeefde bloem met een houten lepel erbij roeren. Op het vuur weer even verwarmen, tot het deeg als een bal van de wand loslaat. Van het vuur één voor één de 2 eieren + 1 dooier bijvoegen. Het deeg moet in brokken van de lepel vallen. Klop het deeg luchtig en glanzend met de mixer. Met 2 lepeltjes (of met de spuitzak) 30 bergjes met een ruime onderlinge afstand op de ingevette bakplaat scheppen of spuiten (mondje 9). De bakplaat in het midden van de oven - 200° - schuiven en de soesjes in 20 - 25 min. goudgeel bakken. Laat ze dan nog 5 min. in de uitgeschakelde en geopende oven staan en laat uitdampen op een rooster. Vul ze met stijfgeklopte en gezoete slagroom, bestuif ze met poedersuiker en versier ze met papieren parapluutjes.', 3, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (52, 'Taart met notenkorst', '175 gram boter|150 gram suiker|Zout|3 eieren|1 eierdooier|200 gram zelfrijzende bloem|1 zakje vanillesuiker|Boter om in te vetten|1 ei|150 gram suiker|200 gram gemalen hazelnoten', 'Klop de boter met de suiker schuimig. Voeg de eierdooiers toe. Meng de bloem en vanillesuiker erdoor. Schep de met zout stijfgeklopte eiwitten er onder. Schep het beslag in een ingevette springvorm van 26 cm .doorsnee. Klop voor de notenkorst het ei en het eiwit, de suiker en een mespuntje zout schuimig. Meng er de gemalen noten door. Schep de massa boven op het beslag in de vorm. Bak de taart in de tot 175° voorverwarmde oven ca. 50 min. Maak de taart uit de vorm los en snijd er 12 punten van.', 3, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (53, 'Tiramisu (klasiek)', '5oo gram Mascarpone Galbani|1.25 dl sterke koffie|4 eierdooiers|2 eiwitten|100 gram poedersuiker|2 cl Amaretto|200 gram boudoirs|3 soeplepels cacaopoeder', 'Schik de koekjes en besprenkel ze met de koffie. Maak een beslag met de eierdooiers, suiker en likeur. Voeg hier de Mascarpone aan toe. Klop het eiwit tot een luchtig schuim en meng het heel voorzichtig onder het beslag. Schik de koekjes in drie lagen en breng tussen iedere laag wat crème aan. Laat het gerecht 2 tot 4 uur in de ijskast staan. Bestrooi het geheel met cacaopoeder alvorens op te dienen.', 7, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (54, 'Gebonden courgette-preisoep', '2 courgettes (+/- 400gram)|2 preien (+/- 400gram)|Zout|1 ui|Boter of margarine|2 eetlepels bloem|1 kruidenbouillontablet|1 dl koffieroom|1 eetlepel citroensap|1 eetlepel dille (diepvries)', 'Courgettes wassen en kroontjes verwijderen. In plakjes snijden. Plakjes in 4 snijden. Preien schoonmaken, in ringen snijden en wassen. Doe courgette, prei, zout en 1/2 l water in pan en breng aan de kook. 5 min. zachtjes laten koken. 16 stukjes cougette uit de pan scheppen en achterhouden voor garnering. Rest nog 10 min. koken. Intussen ui pellen en snipperen. Courgette-preimengsel pureren. Met water aanvullen tot 8 dl. In pan boter verhitten en de ui +/- 3 min. zachtjes bakken. Bloem erdoor roeren en al roerende scheutje voor scheutje prei-courgette- mengsel toevoegen. Blijven roeren tot de soep gebonden is.Bouillontablet erboven verkruimelen. +/- 5 min. zachtjes koken. Koffieroom, citroensap en dille toevoegen. Op smaak brengen met peper en zout. In 4 soepkommen scheppen. Garneren met courgetteplakjes. Je kan ook verse bouillon gebruiken en inplaats van dille kan je peterselie nemen.', 10, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (55, 'Gevulde kippesoep', '1 kip van ca. 1.200 kg|1 grote prei|2 takjes groene selder|laurier|1 dikke ui|100 gram spek|Solo|50 gram rijst|300 gram wortelen|Peterselie|50 gram geraspte parmezaan|Peper en zout', 'Leg de kip in 2 l. water en breng aan de kook, samen met het groene gedeelte van de prei, in grove stukken gesneden, de blaadjes van de selder en het laurierblaadje. Na 30 min.koken,neemt u de kip uit de bouillon en test of ze gaar is. Laat de bouillon 15 min. verder koken en giet hem door de zeef. Snipper de ui fijn en snij het spek in dobbelsteentjes. Laat een beetje Solo smelten in een grote pan en fruit daarin de ui en het spek. Overgiet met de bouillon en voeg de rijst (vermicelli) toe. Snij de wortelen in julienne en voeg ook deze bij de bouillon. Na 10 min. koken, voegt u er ook de klein gesneden prei, de selder en peterselie bij. Ondertussen ontbeent u de kip en snijdt u het vlees in reepjes. Voeg dit net voor het einde van de kooktijd bij de soep. Breng op smaak met peper en zout. Bestrooi de soep met parmezaan en eet er stokbrood bij.', 10, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (56, 'Moeders groentesoep', '--- Bouillon: ---|2 l water|1 ui|worteltjes|Wat peterselie - bladselderij - laurierblaadje - stukje foelie|Een kruidnagel|Gehakt|Paneermeel|Zout en peper|Nootmuskaat|--- Soepgroenten: ---|Bloemkool - ui - knol)selder - sperzieboontjes - worteltjes - prei|Champignons - spruitjes - vermicelli.', 'Trek een stevige bouillon met het vlees de groenten en de specerijen. Intussen meng je voor de balletjes het gehakt, met peper, paneermeel,zout en nootmuskaat. Voeg de groenten, gehaktballetjes, indien gewenst het in kleine stukjes geneden soepvlees toe. Op het laatst de champignons en de vermicelli mee gaarkoken. Nog enkele vleesbouillon blokjes naar smaak toevoegen. Afwerken met peterselie en bladselderij. Eventueel nog wat zout en peper.', 10, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (57, 'Goelasj-soep', '1/2 kg runderstoofvlees (in kleine stukjes verdeeld)|300 gram uien|1/2 dl olie|paprikapoeder|1 eetlepel tomatenpuree|1 dl rode wijn|1 l bouillon|2 knoflook-teentjes|Groene kruiden|4 grote aardappelen|Zout en peper|1 laurierblad|worteltjes', 'Uien pellen en fijn snipperen. Olie verhitten en de uien goudbruin fruiten. Aanlengen met tomatenpuree en verwarmen tot de saus begint te bruinen. Roer er het paprika poeder door en laat even, op een hoge vlam, bakken. Leng aan met rode wijn en een kopje van de bouillon. Laat 10 min. pruttelen en doe er dan de stukken vlees bij en laat even bruinen in de saus. Voeg de worteltjes, de specerijen en de overige bouillon bij. Sluit de stoompot en laat 30 min. stomen. Voeg er dan de in blokjes gesneden aardappelen bij en laat nog even gaar worden. Kruid de soep naar smaak en versier met het in flinterdunne reepjes gesneden vruchtvlees van de paprika''s. Slechts heel even verhitten. Lekker, goed als maaltijdsoep.', 10, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (58, 'Mexicaanse soep', '100 g.ui|1 groene paprika|2 rode paprika''s|Doosje tomatenpuree|500 gram mais|300 gram hesp in een klomp|Bouillon', 'Ui, hesp en groene paprika in stukjes laten stoven in wat boter. 1 l. hete bouillon toevoegen. 15 min. op stil vuurtje laten sudderen. Daarna maiskorrels + vocht + rode paprika in blokjes gesneden toevoegen + 3 eetl.tomatenpuree. Laten doorkoken, kruiden met zwarte peper, tijm en look. Eventueel kun je ook nog worteltjes en erwtjes of boontjes toevoegen.', 10, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (59, 'Kerriesoep met mosselen', '1 1/2 eetlepel boter|3 eetlepels gehakte ui|1 1/2 eetlepel bloem|1 kleine eetlepel kerriepoeder|1 dl. verse room|250 gram gekookte mosselen uit de schelp|Versgemalen peper en zout', 'Fruit de ui aan in de boter, roer er de bloem en de kerrie door, laat even meestoven en overgiet met de bouillon en gezeefde kookvocht. Roer en laat zachtjes wat indikken. Roer er de verse room door en kruid met peper en zout. Voeg er net voor het serveren de mosselen bij en laat die even opwarmen in de soep.
Serveer met vers stokbrood.', 10, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (60, 'Mosterd-vissoep', '½ ui|250 gram aardappelen|Boter|2 tl. kerriepoeder|1 kruidenbouillontablet|150 gram kabeljauwfilet|1 bosuitje|1 ½ el. grove mosterd|1 ei|3 eetlepels room|1 eetlepel citroensap|1 takje peterselie|Zout en peper', 'Ui snipperen, aardappelen schillen en in stukjes snijden. Boter smelten . Ui en kerriepoeder +/- 3 min. bakken. Aardappelen, bouillontablet en ½ l. water toevoegen en 25 min. zachtjes laten koken. Door zeef wrijven. (Ik mix het even) Met water aanvullen tot 7 dl. Vis in reepjes snijden. Van bosui buitenste blad verwijderen, en in dunne ringen snijden. Soep en mosterd door elkaar roeren. Vis toevoegen en aan de kook brengen. Met deksel op de pan ongeveer 6 min. zachtjes koken. Intussen ei splitsen en de dooier loskloppen met de room. Van het vuur af al roerende aan de soep toevoegen. Citroensap en bosui erdoor roeren. Op smaak brengen met peper en zout en fijngehakte peterselie er over strooien', 10, 4560);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (61, 'Pompoensoep', 'Pompoen|ui|prei|Room|Peper en zout|Bouillon|Peterselie', 'Pompoen schillen, pitten verwijderen en in blokjes snijden. De ui(en) fijn snijden en in de boter goudgeel bakken. De pompoen even mee stoven. De in ringen gesneden prei toevoegen. De bouillon erbij gieten en alles gaar koken. Even mixen. Room ,peper en zout toevoegen en nog even laten doorkoken. Flink met peterselie bestrooien.', 10, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (62, 'Soep met Maredsous kaas', '3 grote uien|3 teentjes knoflook|3 grote aardappelen|1 klein blikje tomatenpuree|3 blokjes vleesbouillon|1 vlootje Maredsous Dubbelroom smeltkaas (200g)|1.5 l. water', 'Pel de uien, schil de aardappelen en snijd ze fijn. Pers de teentjes knoflook uit. Doe het water in een kookpan en voeg er de groenten, de knoflook en de tomatenpuree aan toe. Aan de kook brengen. Zodra het kookt, de smeltkaas en de bouillonblokjes toevoegen en goed roeren. Zodra het geheel opnieuw kookt, 30 min. op een zacht vuur laten koken.
Daarna mixen. Heet serveren, versierd met wat gebakken stukjes brood en peterselie.', 10, 11678);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (63, 'Groentesoep met salami', 'Broccoli|Bosuitjes|Cherry-tomaatjes|Wortels|Champignons|Vermicelli|Servelaatworst|Teentje knoflook|Wat spinazieblaadjes|Verse bouillon en bouillonblokjes|Tijm|Rozemarijn', 'Verdeel de broccoli in roosjes, snij de bosuitjes schuin in kleine stukjes, en de tomaatjes in de helft, de worteltjes in plakjes (mooie ribbels krijg je als je een ribbelmesje gebruikt) en de champignons in dunne plakjes. Dompel de spinazie even in heet water en leg er een knoopje in. Doe de champignons, worteltjes, bosuitjes, tijm en rozemarijn en knoflook en de bouillonblokjes in de hete bouillon. Even laten doorkoken. Haal de rozemarijn en tijm eruit en doe er peper en zout bij. Voeg pas op het laatste moment de salami en de tomaatjes toe.', 10, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (64, 'Zuiderse groentensoep', '1 l. kippebouillon|1 groene en 1 rode paprika|1 kleine courgette|1 kleine venkelknol|1 aubergine|2 eetlepels olijfolie|1 knoflookteentje|1 eetlepel gehakte basilicum|Zout', 'Was de groenten, verwijder zaad en zaadlijsten van de paprika''s. Snij het venkelgroen van de knol. Snij de groenten in heel kleine stukjes. Fruit het geperste knoflookteentje glazig in de hete olie. Voeg de groentejulienne toe en roerbak 2 min. Giet er de kippebouillon bij, breng aan de kook en laat (hooguit) 10 min. sudderen. Breng op smaak en garneer de soep met de gehakte basilicum. Een soepje dat u zowel warm als lichtjes gekoeld kunt serveren. Geef er wat knoflook-stokbrood bij.', 10, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (65, 'Chop choy - Filipijnse stijl', '1 pak ''stir fry chop choy mix'' (verkrijgbaar in de beter Aziatische winkel)|1 glas water|1/2 Kg vlees in serveerbare stukjes gesneden|2 eetlepels bakolie|1/2 Kg gemengde groenten zoals o.a. bloemkool - broccoli - paprika - championnen - mais - sojascheuten - ui en/of wortelen', 'Los de ''stir fry chop choy mix'' op in water. Breng de olie op temperatuur in een wok en voeg groenten en vlees bij. Doe de opgeloste chop choy mix er ook bij en laat koken boven een heet vuur tot de saus dik wordt en de groeten zacht zijn.', 1, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (66, 'Pancit Canton - Filipijnse stijl', '227g Canton noedels (verkrijgbaar in de betere Aziatische winkel)|1/4 Kg vlees in kleine stukjes gesneden|2 eetlepels bakolie|Gemengde groenten: platte bonen - rode paprika''s - chinese cool - ui en wortelen|beetje knoflook|pancit canton mix (verkrijgbaar in de betere Aziatische winkel)', 'Leg de Canton noedels in kokend water gedurende 1 minuut. En laat nadien uitlekken in een vergiet. Warm olie op in een wok en voeg knoflook en ui toe. Vervolgens het vlees met de groenten mix en de noedels met de pancit canton mix. Laat alles gedurende 2 minuten goed doorkoken.', 1, 4226);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (69, 'Pasta met spinazie en roomkaas', '200-250 gram pasta - bijv. tagliatelle|1 groentenbouillonblokje|200 gram gare gehakte uitgelekte spinazie (uit blik)|1 gesnipperd sjalotje|100 gram roomkaas|6 blaadjes verse basilicum (of 1 theelepel gedroogde)|peper - zout en paprikapoeder|olijfolie', 'Kook de pasta in ruim water met het groentebouillonblokje en een scheutje olie. Bak intussen het gesnipperde sjalotje zachtjes aan en voeg de spinazie en de roomkaas toe. Blijf voortdurend roeren tot de kaas is gesmolten. Voeg evt. wat water toe als de saus te dik is en peper, zout en paprikapoeder naar smaak. Op het laatst de basilicum, fijgewreven of gescheurd, toevoegen. Pasta afgieten en met de saus vermengen, opdienen met een frisse salade.', 9, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (70, 'Kaastaart met frambozen', '200 g speculaas|75 g boter|10 g gelatine (ongeveer 5 blaadjes)|1 dl water|8 eetlepels suiker|2 zakjes vanillesuiker|25 cL verse room|300 g frambozen|200 g verse kaas', 'Doe de speculaasjes in een plasticzak en verkruimel ze met een deegrol. Maak de boter zacht (au bain-marie smelten of kort in de magnetron. Doe de verkruimelde speculaas in een kom, voeg er de boter aan toe en vermeng goed. Bekleed de bodem van een bakvorm of een springvorm (doorsnede 20 cm) met boterpapier en strijk het koekjesdeeg erop open. Dompel de blaadjes gelatine in water tot ze lichtjes verrimpelen. Laat deze blaadjes vervolgens volledig smelten in het water op een zacht vuurtje, zonder te koken. Voeg de suiker toe, meng en laat afkoelen. Vermeng de verse kaas met de vanillesuiker. Voeg de afgekoelde gelatine met suiker toe en roer goed. Klop de verse room stijf en schep hem voorzichtig onder het kaasmengsel. Mix de frambozen en schep ook de frambozenmousse voorzichtig onder het kaasmengsel. Doe het hele beslag in de bakvorm en laat 24 u opstijven in de koelkast. Smakelijk!', 3, 5387);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (71, 'Venkel en wortels gestoofd in witte wijn', '3 knollen venkels|4 wortels|zonnebloemolie|1.5 tl dillezaad|peper|zout|1.2 dl witte wijn', 'Snijd de groenten in stukjes. Stoof ze in de verhitte olie gaar, samen met de kruiden. Blus alles met de witte wijn, laat de alcohol verdampen, en serveer.', 11, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (75, 'Gluhwein', '1 liter rode wijn|5cl cognac of bruine rum|1 citroen|1 sinaasappel|2 eetlepels honing|100 gram rietsuiker|2 kruidnagels|een stokje kaneel', 'Giet de wijn in een kookpot. Voeg daarbij de citroen en de sinaasappel, die met schil en al in stukjes is gesneden. Roer ook de suiker en de honing er onder. Breng op smaak met de nodige kruiden. Verwarm het mengsel tot het net niet kookt maar wel veel damp te zien is. Hoe langer de drank kookt, des te meer verdampt de alcohol en gaat de smaak verloren. Zet de kookplaat af en laat de vloeistof nog een 30 minuten trekken. Giet daarna door een zeef en voeg er op het laatste nog 2 glaasjes rum of de cognac toe. Laat nog even opwarmen. Serveer voorzichtig in de glazen. Om de glazen te beschermen tegen barsten, zet je in het glas eerst een koffielepeltje.', 2, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (76, 'Courgettecarpaccio met gedroogde tomaat', '1 courgette|4 gedroogde tomaten in olie|bosje verse basilicum|4 eetlepels olijfolie|1 1/2 el citroensap|1 teentje knoflook|1/4 eetlepel zout|zwarte peper', 'Gedroogde tomaten in reepjes snijden. Basilicumblaadjes fijnknippen en tomaat erdoor scheppen. Dressing: in afsluitbaar potje olie en citroensap doen. Knoflook erboven uitpersen. Op smaak brengen met zout. Even goed schudden. Courgette wassen. Met kaasschaaf schuin in dunne plakken schaven. Vier borden dun bestrijken met dressing. Courgetteplakken dakpansgewijs op borden leggen. Rest van dressing erover sprenkelen, zodat alle plakjes bedekt zijn. Ca. 10 minuten laten staan. Courgetteplakken bestrooien met peper. Gedroogde tomaat met basilicum erover verdelen.', 10, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (77, 'Donuts', '20 gram gist|1 eetlepel suiker|1/2 deciliter lauw/warm water|50 gram boter|1/4 liter warme melk|150 gram suiker|1/2 theelepel nootmuskaat|2 theelepels zout|2 grote losgeklopte eieren|500 gram bloem 50 gram suiker', 'Los de gist op met de eetlepel suiker in het warme water. Laat de boter in de melk smelten en giet de tot lauw afgekoelde melk bij het water met de gist. Voeg de vier volgende ingredienten toe. Kneed de bloem met de vloeistof tot een zacht deeg. Laat het deeg toegedekt op een warme plaats rijzen. Vorm van het deeg dan kleine ballen en duw er in het midden een gat in met de steel van een houten lepel. Laat ze zo nog 40 minuten op een warme plaats staan en bak ze dan in de hete frituur goudbruin. Laat ze op keukenpapier uitlekken en wentel ze dan door het mengsel van suiker en kaneel.', 6, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (78, 'Everzwijnragout', '800 g everzwijnfilets|1 wortel|1 pakje boleten - gedroogde|10 jeneverbessen|4 cl cognac|2 dl wildfond|5 dl wijn|rode|boter (of olie)|1 kl olijfolie|2 blaadjes laurier|1 sjalot|2 el bloem|1 takje tijm|4 el aalbessengelei|2 kruidnagels|1 ui|2 knoflookteentjes|peper|zout', 'VOORBEREIDING: Pel en snij de ui in grove stukken. Snij de wortel in plakjes. Pel en plet de knoflookteentjes. Snij de everzwijn in stukjes. BEREIDING: Vermeng alle ingrediënten- ui, wortel, knoflook, jeneverbessen, kruidnagels, laurier, tijm, wijn en olijfolie-  voor de marinade. Doe er het vlees bij. Zet afgedekt in de koelkast. Laat een nacht marineren. Dep het gemarineerde vlees goed droog. Zeef de marinade. Braad de stukjes vlees snel rondom aan in boter of olie. Doe er de sjalotsnippers bij. Roerbak 1 minuut. Strooi er de bloem bij. Schep goed om. Kruid met peper en zout. Schenk er de cognac bij en laat op een vrij hoog vuur de alcohol verdampen. Blus met de wildfond en voeg er zo veel gezeefde marinade aan toe tot het vlees net onderstaat. Doe er de gedroogde boleten bij. Dek af en laat 1 tot anderhalf uur stoven. Roer de aalbessengelei door de saus. Kruid eventueel nog wat bij. Serveer goed heet. TIP: Lekker met appeltjes uit de oven, gevuld met cranberry''s, en met kroketten', 13, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (79, 'Kervelsoep met oesterzwammen', '1 bakje oesterzwammen (150 g)|2 kruidenbouillontabletten|1 zakje verse kervel (15 g)|zwarte peper', 'In een pan 1 liter water aan de kook brengen. Intussen de oesterzwammen schoonvegen met keukenpapier en in reepjes snijden. Bouillonblokjes boven kokend water verkruimelen en ca. 3 minuten laten doorkoken. 
Boven een kopje kervel fijnknippen. Soep op smaak brengen met peper. 
Kervel erdoor roeren. 
Soep in vier diepe borden scheppen.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (80, 'Shii-Take Soep', 'Shii-Take (Japanse paddestoelen)|peper|zout', 'Kook de paddestoelen in de bouillon en laat ze minstens 20 minuten zachtjes pruttelen. 
De soep is dan in principe klaar, maar het lekkerste is deze soep als ie ''s morgens al is bereid en nog de hele dag staat. 
''s Avonds hoeft ze alleen nog maar opgewarmd te worden en de krachtige smaak van de shii takes is dan door de gehele bouillon getrokken. 
Breng de soep op smaak met peper en zout', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (81, 'Paddestoelensoep', '1 bakje oesterzwammen (150 g)|1 bakje shii-takes (100 g)|1 sjalotje|1 eetlepel boter of margarine|1 theelepel ketjap manis|2 kruidenbouillonblokjes|1 dl dry sherry', 'In fluitketel of pan 7 dl water aan de kook brengen intussen paddestoelen schoonvegen met keukenpapier en in reepjes snijden. Sjalotje pellen en fijnsnipperen, in koekenpan boter verhitten en sjalot, paddestoelen en ketjap al omscheppend ca. 3 minuten bakken. Paddestoelmengsel overdoen in ruime pan. Kokend water erbij schenken. Boullionblokjes erboven verkruimelen, goed doorroeren. Sherry toevoegen en soep onafgedekt ca. 3 minuten zachtjes door laten koken.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (82, 'Bouillon van paddestoelen', '500 gr runderschenkel|4 liter water|250 gr ui|prei|wortel|5 peperkorrels|1 blad laurier|100 gr blanke champignons|100 gr champignons de Paris|100 gr shi take|100 gr pleurottes|10 gr zout|50 gr verse kervel', 'De schenkel met koud water opzetten , aan de kook brengen en afschuimen. 
Ui, wortel,prei, klein snijden wassen en met de champignonstelen toevoegen aan de bouillon. 
De bouillon laten inkoken tot 2 liter dan passeren. 
Champignons voor gebruik schoonborstelen en in dunne plakjes snijden. 
De champignons 5 min mee laten garen. 
Op smaak brengen met peper en zout en voor het serveren de geplukte kervel toevoegen.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (83, 'Paddestoelen soep 2', '250 gr. mergelchampignons|150 gr. oesterzwammen|100 gr. cantharellen|1 ui|50 gr. boter|30 gr. bloem|1 liter bouillon|1 eidooier|2 eetlepels|koffieroom|zout|peper|scheutje droge witte wijn', 'Pel en snipper de ui. Maak de paddestoelen schoon en snij ze aan reepjes, plakjes. Smelt in een braadpan 20 gr. boter, fruit hierin de ui. Voeg de paddestoelen toe en laat ze rnet een deksel op de pan in + 10 min. gaarsmoren. Smelt in een andere pan 30 gr. boter en roer de bloem erdoor. Schenk een deel van de bouillon erbij en blijf roeren tot een gladde massa ontstaat. Voeg op dezelfde wijze de rest van de bouillon in gedeelten toe. 
Roer de paddestoelen met het vocht door de soep. Voeg een losgeklopt ei- dooier al roerend door de soep. Verwarm de soep zachtjes tot die gebonden is, maar laat het niet meer koken. Breng de soep op smaak met zout en peper. Eventueel en scheutje wijn. Dit gerecht kunt u uitstekend van te voren klaar-maken. Alleen het mengen met eidooier moet u op het laatste moment doen.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (84, 'Oesterzwam soep met paprika en mais', '250 gr. oesterzwammen|2 eetlepels boter|1 theelepel basilicum|3 eetlepels bloem|2 groentebouillontabletten|1 rode paprika|1 blik mais (340 gr.)|1 ei|2 eetlepels medium sherry', 'Van paddestoelen onderkant van steeltjes verwijderen. In reepjes snijden. In pan boter smelten. Paddestoelen ±5 minuten bakken. Basilicum en bloem erover strooien. Al roerende 1 liter heet water toevoegen. Blijven roeren tot gebonden soep. ouillontabletten toevoegen. Met deksel op pan ± 5 minuten zachtjes koken. Paprika wassen. Zaadlijsten verwijderen en in stukjes snijden. Mais afgieten. Aan soep paprika en mais toevoegen. 
In ± lO minuten zachtjes verwarmen. Af en toe roeren. 
Intussen in kommetje ei loskloppen. Soep van vuur nemen. 4 eetlepels soep door ei roeren. Al roerende eimengsel aan soep toevoegen. Sherry er door roeren. Soep over 4 borden verdelen.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (85, 'Heldere cantharellen soep met bladerdeeg', '250 gr . cantharellen|1 sjalotje|25 gr . boter|1/4 theelepel tijm|1/4 theelepel|oregano|1/4|theelepel salie|1 blik heldere ossestaartsoep|5 eetlepels|rnadera|worcestershiresaus|versgemalen peper|4 plakjes|diepvries|bladerdeeg|1 ei', 'Cantharellen schoon maken,grote in stukjes snijden. 
Sjalotje pellen en heel fijn snijden. In een pan boter verhitten. 
Sjalotje ±2 min. zachtjes bakken. Toevoegen: cantharellen, tijm, oregano en salie. ±10 min. zachtjes meebakken, af en toe roeren. Soep,niet verdunnen, erboven zeven. Erdoor roeren: madera, enkele druppels worcestershiresaus en peper. Van vuur nemen. Laten afkoelen en tot gebruik afgedekt koel wegzetten. Oven voorverwarmen op 200 c° 
Bladerdeeg uitspreiden en in 10 min. laten ontdooien. Boven 2 kommetjes ei splitsen en 1 eetlepel water door het dooier roeren. 4 ovenvaste soepkommetjes vullen met cantharellensoep. Hoekjes van bladerdeeg eraf snijden, zodat ronde plak ontstaat ±2 cm. groter dan soepkommetjes. 
Bladerdeeg en randen van kommetjes bestrijken met eiwit. 
Bladerdeeg met eiwitzijde naar beneden op soepkommetjes leggen, randen goed aandrukken. Bladerdeeg bestrijken met dooiermengsel. In het midden van de oven in ±15 min. gaar en heet laten worden. Direkt opdienen.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (86, 'Wild soep met paddestoelen', '50 gr . in kleine blokjes|gesneden ontbijtspek|paddestoelen (mergelchampignons - cantharel - eekhoorntjesbrood)|1 ui klein gesneden|1 eetlepel bloem|1 lit. wildbouillon|0.5 dl. port|0.5 dl. slagroom|zout|peper|1 eetlepel fijngehakte peterselie', 'Bak de blokjes spek uit in een flinke pan. Voeg de olie toe en verhit deze. 
Fruit de stukjes paddestoel en de klein gesneden ui ca. 3 min. in het spek-oliemengsel. Roer de bloem door het mengsel. Voeg onder voortdurend roeren beetje bij beetje de bouillon toe tot een gebonden soep is ontstaan. 
Draai de hittebron laag, leg een deksel op de pan en laat de soep ca. 15 min. zachtjes koken. Roer de port en de slagroom door de soep en maak alles op smaak met wat zout en peper. 
Serveer de soep bestrooid met de fijngehakte peterselie.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (87, 'Roergebakkenbroccoli en oesterzwammen', '1/2 pak pandanrijst (à 250 g)|3 bosuitjes|1 zakje broccoliroosjes (300 g)|1 bakje oesterzwammen (150 g)|3 eetlepels oosterse roerbakolie|2 eetlepels sojasaus|150 g gezouten cashewnoten', 'In pan 4 dl water aan de kook brengen. Rijst toevoegen en afgedekt in ca. 10 minuten gaar koken. Intussen bosuitjes schuin in stukken van ca. 2 cm snijden. Broccoli in kleinere roosjes verdelen. Oesterzwammen schoonvegen met keukenpapier en halveren. In wok roerbakolie verhitten. Bosui, broccoli en oesterzwammen erdoor scheppen en ca. 3 minuten al omscheppend bakken. Sojasaus en 1/2 dl water toevoegen en groente in nog ca. 4 minuten gaar laten worden. Cashewnoten door groente scheppen. Rijst in vier wijde kommen scheppen en roergebakken groente erop scheppen.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (88, 'Lasagne met paddestoelen', '50 g Parmezaanse kaas (stukje)|zout|1 bakje oesterzwammen (150 g)|1 bakje grotchapignons (250 g)|1 bakje cantharellen (100 g)|2 eetlepels droge witte wijn|2 1/2 eetlepel (walnoot)olie|ca. 1 thelepel zwarte en rode peper (McCormick)|1 zakje waterkers (75 g)', 'Kaas raspen. In pan met ruim koken water en zout lasagnevellen in ca. 8 minuten beetgaar koken. Intussen paddestoelen schoonvegen met keukenpapier. Oesterzwammen in dunne reepjes snijden. Champignons in partjes snijden. Cantharellen in plakjes snijden. In pan boter verhitten. Paddestoelen op hoog vuur ca. 5 minuten al omscheppend bakken. Wijn erdoor roeren en op hoog vuur in ca. 1 minuut iets laten inkoken. Van vuur af 2 eetlepel olie erdoor scheppen en paddestoelmengsel op smaak brengen met zout en helft van peper.

Vier borden voorverwarmen. asagnevellen afgieten en in breedte halveren. Besprenkelen met rest van olie. aterkers over borden verdelen. 1/3 Deel van paddestoelen op waterkers scheppen. Hierop helft van lasagnevellen leggen. 
Nogmaals 1/3 deel van paddestoelen op lasagnevellen scheppen. Afdeken met rest van lasagnevellen. Tot slot rest van paddestoelen erop scheppen. Geraspte kaas erover strooien en bestrooien met rest van peper.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (89, 'Varkenshaasje met paddestoelensaus', '1 ui|1 bakje oesterzwammen (150 g)|1 bakje kastanjechampignons (250 g)|50 g bakbacon (vleeswaar)|1 takje peterselie|50 g boter of margarine|4 varkenshaasjes (a 150 g)|zout|peper|1/2 eetlepel tijm|4 eetlepels marsala (slijter)|1 eetlepel sojasaus (chinese emperror)|1/8 liter slagroom', 'Bereidings duur: lang! Maar het resultaat waard. 
Voorbereiden: Halve dag van tevoren. Ui pellen en halveren. Helften in dunne ringen snijden. Paddestoelen schoonvegen met keukenpapier. Taaie steeltjes van oesterzwammen snijden. Grote oesterzwammen in repen snijden. Champignons in plakjes snijden. Bacon in stukjes snijden. In kopje peterselie fijnknippen. 

Bereiden: Vijf borden voorverwarmen. 
In koekepan boter verhitten. Ui, paddestoelen en bacon ca. 5 minuten bakken. Intussen varkenshaasjes schuin in plakken van ca. 2 cm dik snijden. Met vleesmes plakken platslaan. Varkenshaas bestrooien met zout, peper en tijm. Met schuimspaan paddestoelenmengsel uit pan op bord scheppen. In achtergebleven bakvet varkenshaas ca. 5 minuten bakken, halverwege keren. Uit pan op voorverwarmd bord scheppen en onder aluminiumfolie warmhouden. Aan achtergebleven bakvet toevoegen: paddestoelenmengsel, marsala, sojasaus en slagroom. Aan de kook brengen en op hoog vuur nog ca. 2 minuten laten inkoken. Op smaak brengen met zout en peper. Plakjes varkenshaas dakpansgewijs op borden rangschikken. Paddestoelen half erover en erlangs schenken. Bestrooien met peterselie. Serveren met sperziebonen met katenspek en aardappelkroketjes.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (90, 'Kaas-oesterzwam taartje', '4 plakjes bladerdeeg(diepvries)|3 bosuitjes|1 bakje oesterzwammen (150g)|1 eetlepel boter of margarine|2 eetlepels droge witte wijn|2 theelepels tijm|2 eetlepels paneermeel|100g geraspte oude kaas (zakje a 150g)|3 eieren|1/2 bekertje crème fraîche (a 125ml)|peper|(1/2 eetlepel boter of margarine om in te vetten|1 eetlepen bloem om te bestuiven)|keukenpapier|4 lage taartvormpjes a doorsnede ca. 10 cm', 'Oven voorverwarmen op 200 graden c of gasovenstand 4. 
Bladerdeeg op aanrecht uitspreiden en in ca. 5 minuten laten ontdooien. 
Intussen bosuitjes schoonmaken en in ringetjes snijden. 
Oesterzwammen schoonvegen met keukenpapier en in reepjes snijden. 
In pan boter verhitten en oesterzwammen op hoog vuur al omscheppend ca. 3 minuten bakken. 
Bosui, wijn en tijm toevoegen en het geheel onafgedekt nog ca 3 laten koken, hierbij vocht laten verdampen. 
Laten afkoelen. 
Intussen vormpjes invetten. 
Aanrecht bestuiven met bloem. 
Plakjes bladerdeeg uitrollen tot vierkanten van ca. 16x16 cm. 
Elk vormpje bekleden met 1 plakje bladerdeeg. Overtollig deeg langs randen wegsnijden. 
Met vork gaatjes in bodem prikken. 
Bodems bestrooien met paneermeel en 2 eetlepels kaas. 
In kom eieren loskloppen met creme fraiche en rest van kaas. 
Op smaak brengen met peper. Oesterzwammengsel erdoor scheppen. 
Mengsel over vormpjes verdelen. 
Taartjes op 1 richel onder midden van oven in ca. 24 a 30 minuten lichtbruin en gaar bakken. Taartjes in vorm ca. 10 minuten laten afkoelen. Taartjes uit vorm nemen en op taartrooster verder laten afkoelen.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (91, 'Paddestoelenpie met ham', '8 plakjes diepvries bladerdeeg|1 bakje oesterzwammen (150 g)|2 sjalotjes|25 g boter|1 tl tijm|200 g beenham blokjes|1 ei|1 blikje kalfragout|1 eetlepel koffieroom|zout|peper', 'Bereidingsduur: ca 15 minuten en 40 minuten in de oven. 
Verwarm de oven voor op 200 graden C. 
Laat het bladerdeeg ontdooien. Snij de shii-takepaddestoelen en de champignons in plakjes, snij de oeserzwammen in repen. 
Snipper de sjalotjes. 
Bak de paddestoelen en sjalotjes tot het vocht verdampt is. 
Voeg tijm, zout en peper toe. 
Rol 5 plakjes deeg uit tot een ronde lap van 30 cm. 
Vet een taartvorm (doorsnede 26 cm) in en bekleed met de deeglap. 
Roer het eid door de ragout en schep de paddestoelen en ham erdoor. 
Verdeel het mengsel over de taartbodem. 
Rol de andere deegplakjes uit tot een lap ter grootte van de vorm. 
Leg de lap over de vulling. 
Druk de rand dicht. 
Maak gaatjes in het deksel. 
Bestrijk de bovenkant met koffieroom. 
Bak de taart in ca. 40 minuten.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (92, 'Pate met oesterzwamdressing', '1/2 krop eikenbladsla|8 eetlepels walnootolie|3 eetlepels (rode wijn)azijn|1 theelepel mosterd|1/2 theelepel suiker|zout|versgemalen zwarte peper|1/4 bakje oesterzwammen a 150 gr.|4 plakken noten-pate a ca. 75 gr.', 'Sla schoonmaken, wassen en laten uitlekken. Olie, azijn, mosterd, suiker, zout en peper tot dressing roeren. 
Oesterzwammen schoonvegen met keukenpapier en heel fijn snijden. 
Door dressing roeren en ca. 5 minuten wegzetten. 
Sla over vier bordjes verdelen. 
Pateplakken in midden erop leggen. Oesterzwamdressing erover scheppen. 
Serveren met toast.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (93, 'Oesterzwammen met peultjes', '1 bakje oesterzwammen 150 gr.|100 g peultjes|4 stoneleeks|1 eetlepel boter of margarine|1/2 eetlepen (mais)olie|2 teentjes knoflook|zout en peper', 'Oesterzwammen schoonvegen met keukenpapier en in reepjes snijden. 
Peultjes schoonmaken en wassen. 
Stoneleeks schoonmaken en in ringetjes snijden. In wok of hapjespan boter en olie verhitten. Knoflook pellen en erboven uitpersen. 
Peultjes toevoegen en ca. 3 minuten al omscheppend bakken. 
Oesterzwammen toevoegen en ca. 3 minuten meebakken. 
Stoneleeks toevoegen en ca. 1 minuut meebakken. Op smaak brengen met zout en peper. 
Lekker bij varkenshaasjes en pommes duchesses, aardappelpureetorentjes.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (94, 'Salade met akkerpaddestoel', '1 krop ijsbergsla|100 gram akkerpaddestoel|(lente) uitje|bieslook', 'Sla wassen en breken. 
Akkerpaddestoel schoon borstelen en in plakjes snijden. 
Uitje fijn snijden, bieslook in stukjes knippen. Meng deze ingredienten door elkaar. 

Dressing: Meng olie, azijn, snufje tijm, mayonaise en een klein beetje suiker door elkaar. 
Schenk de dressing over de salade en klaar is uw salade.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (96, 'Champignonsoep', '400 gram champignons|1 klein teentje knoflook|25 gr boter of margarine|2 kruidenbouillonblokjes|3 druppeltjes citroensap (flesje)|1 dl halfvolle koffiemelk en room', 'Was de champignons. 
Snijd ze in stukjes op de snijplank 
Pel de knoflook en snijdt deze in heel kleine snippertjes op de snijplank. 
Doe de boter in de pan en zet de pan op het fornuis. 
Steek het vuur aan en laat de boter smelten. 
Voeg de champignons en de knoflook toe als het schuim wegtrekt. 
Zet het vuur laag en laat de champignons en knoflook ongeveer 10 minuten smoren, zachtjes bakken. 
Roer af en toe met een houten lepel. 
Voeg het water en de bouillonblokjes toe. 
Zet het vuur hoger. 
Laat de soep ongeveer 5 minuten doorkoken. 
Doe de koffiemelk en het citroensap bij de soep en roer nog even voordat je de soep serveert. 

TIP. Voeg kleingesneden, verse peterselie toe: dit geeft een extra heerlijk smaakje.', 8, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (97, 'Fop paddestoelen', '2 stevige tomaten|1 komkommer|1 blikje tonijn|2 lepels slasaus|een snufje peper zout en paprika poeder', 'Was de komkommer grondig en snijdt de komkommer in vier gelijke stukken. 
Snij de komkommer recht af zodat elk stuk rechtop kan staan. 
Hol elk stuk langs één kant uit met een lepel. 
Laat het vocht van de tonijn weglopen door een vergiet, meng de tonijn met de slassaus en een snufje peper, zout en paprikapoeder. 
Vul de vier uitgeholde komkommerstronkjes met het mengsel. 
Snij de tomaten doormidden, hol de vier helften uit met een lepel, zet ze op de komkommerstronkjes. 
Maak kleine witte puntjes met de mayonaise op de tomatenhoedjes.', 6, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (98, 'Pistache Macaronen', '75g pistaches|125g poedersuiker|2 witten van grote eieren|15g fijne kristalsuiker||55g pistaches|250g poedersuiker|125g zachtgeroerde boter', 'Verwarm de oven voor op 180°C (gasovenstand 4). Hak de pistaches in een foodprocessor, samen met de poedersuiker (dit voorkomt dat het een olieachtige troep wordt) tot een soort meel. Klop de eiwitten tamelijk stijf, maar niet te droog. Strooi er de fijne kristalsuiker op en klop verder tot het eiwit heel stijf is. Spatel het schuim voorzichtig door het pistaches-suiker-mengsel. Spuit kleine rondjes op een beklede bakplaat met een glad spuitje, met een doorsnede van 1cm. Laat ze ongeveer 10 minuten staan, zodat zich een velletje vormt. Zet ze vervolgens in de oven en bak ze 10 tot 12 minuten. ze moeten stevig maar niet te droog zijn. Haal ze uit de oven en laat ze op de plaat afkoelen terwijl je de vulling maakt. Maal de noten en de poedersuiker net als hierboven beschreven in de foodprocessor. Roer de boter romig en blijf roeren terwijl je het notenmeel toevoegt. Zorg dat je een gladde, zachte botercrème hebt. Dan maak je gewoon sandwiches van de makronen met de crème ertussen. Voor 20 stuks, dat wil zeggen 40 twee aan twee op elkaar geplakte makronen.', 3, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (99, 'Kaastaart met speculoos en noten', '250 gr speculoos|125 gr boter|500 gr volle verse kaas|250 gr fijne suiker|100 gr gepelde noten|2 eetlepels bloem|3 eieren|25 cl room', 'Verwarm de oven voor op 180 graden en bekleed intussen een springvorm met bakpapier. Maal de noten en verkruimel de koekskes. Laat de boter smelten (tot ze zacht is, niet tot ze vloeibaar is). Vermeng de koekskes, noten en boter tot een plakkerige pasta en verdeel die pasta over de bodem van de vorm. Meng de kaas met de suiker, de bloem en de eieren. Voeg er dan de room aan toe en roer alles glad. Giet die crème nu over de koekskes-notenbodem. Bak de taart 30 tot 40 minuten in het midden van de oven. Controleer af en toe want ze wordt bovenaan snel nogal te donker.', 3, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (101, 'Veloutesoep Agnes Sorel', '2 st preiwit (grof gesneden)|1 bleekselder stengel (grof gesneden)|2 st Ui (grof gesneden)|100 gr Champignons (grof gesneden)|1.5 l Kippenbouillon of blanke fond|Citroensap|Zwarte peper (versgemalen)|Zeezout|50 gr tarwebloem|40 gr echte boter|Room|1 Eigeel|100 gr Champignons (in plakjes of brunoise)|100 gr gekookte kip (in julienne of brunoise gesneden)|100 gr gekookte of gerookte rundertong (in julienne of brunoise gesneden|je kan de rundertong eventueel vervangen door gekookte of gerookte ham', 'De boter laten smelten in een soeppan, de groenten toevoegen en alles laten fruiten. Bestrooien met de bloem en goed mengen met een lepel. Bevochtigen met de bouillon of fond en al roerende aan de kook brengen. Laat 30 minuten op een zacht vuurtje sudderen. Doe wat water en citroensap in een pannetje en voeg de champignons (voor garnituur) toe. Bedek met bakpapier, leg er een bordje op en kook gaar op een hevig vuur in circa 5 minuten. De soep van het vuur wegnemen, mixen met een staafmixer en door een zeef halen. Garnituur: champignons, tong en kip  aan de soep toevoegen en op smaak brengen met peper, zout en citroensap. Laat het geheel nog twee minuutjes doorkoken. Klop in een kommetje het eigeel los met de room (beide op kamertemperatuur), roer er wat warme maar niet-kokende soep onder. Voeg dit mengsel toe aan de soep, zet terug op het vuur en roer tot de soep terug opgewarmd en mooi licht gebonden is (Niet koken!  Soep waar een liaison wordt aan toegevoegd nooit laten koken, anders zal deze schiften! Men kan natuurlijk altijd het eigeel weglaten).', 10, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (102, 'Broodje met spinazie dipsaus', '1 blik (400 gr) artisjokharten (klein gesneden)|400 gr verse spinazie (zonder steeltjes en klein gesneden)|200 gr roomkaas (In blokjes gesneden)|130 gr mozarella (geraspt of in kleine stukjes)|30 gr Parmezaanse kaas (geraspt)|1/4 theelepel zwarte peper|1 teentje knoflook (geperst)', '20 minuten in oven 180° voor verwarmen en opdienen met stukjes brood', 5, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (103, 'Bounty', '1 Banaan|1-2 eetl. geraspte kokos|30gr pure chocolade (72% cacao of meer)', 'Prak de banaan fijn en meng de kokos door de banaan. Je kan ook meer kokos toevoegen indien je dat lekker vindt. Vorm met je handen bounty repen. Leg ze minstens een uurtje in de vriezer. Smelt de chocolade au bain-marie en haal de bevroren bountys uit de vriezer. Dip ze in de gesmolten chocolade en leg op een bakpapier. Wanneer je alle bountys door de chocolade hebt gehaald leg je het geheel nog even in de vriezer tot de chocolade hard is. Je kan deze voor twee weken bewaren.', 6, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (343, 'American cookies', '250g tarwebloem|8g bakpoeder|120g suiker|100g geraspte chocolade|10g cacaopoeder|1 vanillestokje|200g boter|1 ei', 'Meng de bloem, suiker en het cacaopoeder en voeg daarna de boter (in stukjes) toe. Roer ook het ei erbij. Schraap de zaadjes uit het opengesneden vanillestokje en voeg samen met de geraspte chocolade toe aan het deeg. Meng alles goed en giet het deeg uit om een vel vershoudfolie, dat je een half uurtje laat rusten in de koelkast. Verwarm intussen de oven voor op 175 graden en bekleed de bakplaat met een rol bakpapier. Rol kleine balletjes van het deeg, schik ze op de bakplaat met wat ruimte tussen, druk ze plat en bak ongeveer 20 minuten tot ze gaar zijn.', 6, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (344, 'Chocoladefondue', 'Melkchocolade|pure chocolade|witte chocolade|6 dl room|marshmellows|chocoladesnoepjes|sprinkles|hagelslag|gehakte noten', 'Smelt de chocolade in aparte kommetjes en roer in elk kommetje wat room onder de chocolade. Zet de kommetjes op tafel, rijg de marshmellows op een stokje en dip in je topping naar keuze', 6, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (345, 'Chocoladecups', '150g pure en 150g melkchocolade|50g boter|2-3 el speculaaspasta|zout', 'Smelt de chocolade met de boter en bestrijk papieren cakevormpjes met een laagje. Laat even opstijven in de koelkast. Vul de vormpjes met wat speculaaspasta, leg daarop wat gesmolten chocolade en laat opnieuw opstijven in de koelkast. Werk ze af met een snufje zout en serveer onmiddellijk', 6, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (346, 'Notenpralines', '200g melk- en 200g witte chocolade|100g amandelen en 100g pecannoten', 'Verdeel de noten over een ovenschaal en rooster ze goudbruin op 160 graden. Smelt ondertussen de chocolade, elk in een aparte kom. Dompel de noten met een pincet of vork volledig onder in de chocolade en leg ze op een vel bakpapier. Schuif de bakplaat een kwartiertje in de diepvries of koelkast en bewaar nadien in een afgesloten pot ... of eet ze gewoon lekker op!', 6, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (347, 'Kippensoep met rode kerrie', '500 ml kippenbouillon|100 gr kippendijvlees|1 pomodori tomaat|30 gr sojascheuten|1 bosui|1/2 wortel|stengel bleekselderij|1 el rode currypasta|25 gr maiskorrels|handje koriander|1 tl zonnebloemolie|Snufje zwarte peper', 'Verwarm de over voor op 180 graden. Verwarm de kippenbouillon. Meng de kippendij met de zonnebloemolie en de zwarte peper, bak dit ca. 15 minuten in de oven, laat afkoelen en snijd in dunne reepjes. Snijd de koriander fijn, de tomaten in blokjes, de winterpeen in reepjes, de bleekselderij in reepjes en de bosui in dunne ringen. Voeg aan de kippenbouillon de wortel, de bleekselderij en de rode currypasta toe en kook de bouillon kort. Voeg de tomaat, de kipreepjes, de sojascheuten, de maïskorrels en de bosuien aan de kippenbouillon toe en warm kort op. Garneer met de koriander.', 10, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (355, 'Havermoutkoekjes', '200 g havermout', 'Meng alle ingrediënten in een kom. Verwarm de oven voor op 175 Â°C. Maak kleine balletjes en druk ze plat op een bakplaat tot koekjesvormige vormen. Bak 25 minuten', 6, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (359, 'Tiramisu met aardbeien', '500 g mascarpone|2 eieren|2 bakjes aardbeien|50 g suiker|1 blaadje gelatine|1 dl aardbeienlikeur|aardbeiencoulis', 'Week het blaadje gelatine in koud water. Klop de eierdooiers met de suiker tot een bijna witte, luchtige massa (+/- 8-10â). Verwarm de aardbeienlikeur en los er de uitgeknepen gelatine in op. Vermeng de mascarpone met het eierdooiermengsel en de aardbeienlikeur. Klop de eiwitten stijf en spatel ze door het mascarponemengsel. Schik een laag gehalveerde aardbeien in een springvorm en giet er 1/3 van het kaasmengsel op. Maak op dezelfde manier 3 lagen, tot alles opgewerkt is. Zet tenminste 3 uur in de koelkast om op te stijven. Garneer de tiramisu met enkele mooie aardbeien en verse munt. Serveer met aardbeiencoulis.

Je kan ook in plaats van aardbeienlikeur een handvol aardbeien nemen, gemixt en gezoet. Vervolgens een scheutje cognac verwarmen en daar de gelatine in oplossenen en onder de aardbeien mengen.

Diepvries fruit (frambozen of gemengd rood fruit) 100 g bloemsuiker  met  1 dl water aan de kook brengen, het fruit er 5 min in laten sudderen en laten afkoelen. Het sap van het diepvriesfruit onder de mascarpone scheppen i.p.v. gemixte aardbeien.

Suggestie: vul de bodem van longdrink glazen met aardbeien en laag tiramisu, vul het glas in lagen en versier met verse aardbeien en verse munt of met het diepvriesfruit.  Lijkt me ook wel mooi feestelijk dessertje.', 7, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (360, 'Advocaat', 'Blik gecondenseerde melk (305ml)|10 eidooiers|205gr. Suiker|20gr. Vanillesuiker|200ml alcohol 90 graden.', 'Klop in een ruime kom de eidooiers los met de gecondenseerde melk. Doe er de suiker en vanillesuiker bij en roer goed om.Zet een steelpan met water op het vuur en breng aan de kook. Zet de kom op de pan met warm water. De kom mag het water niet raken, want dan krijg je roerei. Begin meteen te kloppen. Klop voortdurend tot het mengsel indikt. Voeg tenslotte beetje bij beetje de alchol toe en klop telkens goed door. Verdeel over bokaaltjes en laat afkoelen.', 2, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (361, 'Advocaat mascarpone mousse', '6 eetlepel advocaat|3 eieren|2 eetlepel suiker', 'Eidooiers met suiker wit kloppen. Mascarpone toevoegen. Advocaat toevoegen. Eiwit stijfkloppen en aan het mengsel toevoegen. Zorg dat het geheel heel luchtig blijft. Verdelen over de glaasjes.', 7, 0);
INSERT INTO recipe (id, title, ingredients, preparation, category_id, view_count) VALUES (362, 'Uiensoep', '6 grote uien|dun gesneden|50 gram ongezouten boter|2 teentjes knoflook|fijngehakt|100 ml witte wijn|1 liter runderbouillon|4 sneetjes stokbrood|100 gram geraspte GruyÃ¨re kaas|Takjes verse tijm (voor garnering)|2 eetlepels cognac (optioneel)|Zout en peper naar smaak', 'Smelt de boter in een grote pan op middelhoog vuur. Voeg de olijfolie toe om te voorkomen dat de boter verbrandt. Voeg de gesneden uien toe aan de pan en bak ze langzaam goudbruin, dit duurt ongeveer 25-30 minuten. Roer af en toe om te voorkomen dat ze aanbakken. Het karamelliseren van de uien is een essentieel onderdeel van het recept, dus neem je tijd! Voeg de knoflook toe en bak deze mee voor nog eens 1-2 minuten. Blus af met witte wijn en roer de aanbaksels van de bodem van de pan los. Laat de wijn 2 minuten inkoken. Voeg de runderbouillon toe en breng de soep aan de kook. Zet het vuur laag en laat de soep 20-30 minuten zachtjes pruttelen. Proef en breng op smaak met zout en peper. Optioneel: Voeg de cognac toe voor extra diepte in de smaak. Verwarm de oven voor op 180 graden. Rooster het stokbrood lichtjes in de oven totdat het knapperig is, ongeveer 5 minuten. Schenk de soep in ovenbestendige kommen. Leg een sneetje geroosterd stokbrood op de soep en strooi er een royale hoeveelheid geraspte Gruyere overheen. Zet de kommen in de oven en laat de kaas smelten en licht goudbruin worden, ongeveer 10 minuten. Haal de soep uit de oven en garneer met verse tijm. Serveer meteen.', 10, 0);
