CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL UNIQUE,
    display_order INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE recipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id INTEGER NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    category_id BIGINT NOT NULL,
    ingredients TEXT NOT NULL,
    preparation TEXT NOT NULL,
    pdf_slug VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_recipes_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE INDEX idx_recipes_category_id ON recipes(category_id);
CREATE INDEX idx_recipes_title ON recipes(title);
